### ISSUE TITLE
Document errors

### ISSUE THREAD

**Issue by gbr746** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#1]
# Module: 00
#### Step: 00

1. C:\Users\Abc\Documents\Devops\Code\virtual-environments\images\win\scripts\Installers\Install-VS.json is the correct file name to install VS
2. az400m05-vm0.deployment.template.parameters.json is the correct filename with the parameters. 
3. The project name in Exercise 0 is Integrating Azure Key Vault with Azure DevOps and not Configuring Agent Pools and Understanding Pipeline Styles
(4. C:\Labview does not exist, but can be set to any directory where the repo was cloned if you do not want to clone to C:\)

Repro steps:

1. N/A
1.
1.

**Comment by polichtm** [comment]
1. Running the following would determine the location of the files (added the New-Item cmdlet to account for 4):
    New-Item -Type Directory -Path 'C:\Labfiles' -Force
    Set-Location c:\Labfiles
    git clone https://github.com/actions/virtual-environments.git virtual-environments -q
the rest has been updated
rgds
Marcin
