### ISSUE TITLE
Lab 10a Stage Canary Environment fails with error for "Enable Continuous Monitoring"

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#105]
# Module: 10
### Exercise: 02

Description of issue
The stage Canary Environment fails due to an issue with the task "Enable Continuous Monitoring", Error message is:

Error: Failed to enable continuous monitoring. Error: Error: Failed to update Application Insights 'PU234457724-Canary' Resource. Error: BadRequest - WorkspaceResourceId can be set only on api-version 2020-02-02 (CODE: 400)

This is also file as a task issue:
https://github.com/microsoft/azure-pipelines-tasks/issues/14794

**Comment by jeyk** [comment]
I ran into this issue, too. My workaround was to just disable the task "Enable Continuous Monitoring" and configure the Web Test manually in Azure. After that, I could complete the lab.

**Comment by krasmuss** [comment]
Under review.

**Comment by ConcreteGannet** [comment]
#14794 has been closed - it's a dupe of
[#15188](https://github.com/microsoft/azure-pipelines-tasks/issues/15188)

**Comment by raphasi** [comment]
I keep having the same error while running this AZ-400 Course Module 10 lab, is there any solution?

**Comment by jeyk** [comment]
> I keep having the same error while running this AZ-400 Course Module 10 lab, is there any solution?

Yes, see [my comment above](#issuecomment-883951109).
