### ISSUE TITLE
LAB 15 & 16 - Docker. Docker Image missed

### ISSUE THREAD

**Issue by JuanQuijano** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#111]
# Module: az-400
#### Step: 00

Description of issue

In the Build task, from the CI pipeline, it looks for a microsft / aspnetcore: 1.0-2.0 image that no longer exists and prevents both labs from being able to start as soon as possible.
Repro steps:

1.
1.
1.

**Comment by Hollyazurespain** [comment]
My student, Carlos Lopez Perez, and I find a temporal solution:
In Repos-Files.
Go to docker-compose.ci.build.yml and change the image microsoft/aspnetcore by paultrampert/aspnetcore-build-with-yarn
The same in src-> MyHealth.Web-> Dockerfile

This image includes the .net core 3.0 sdk and allows the construction of the image necessary to perform both labs.

We hope it helps.

**Comment by JuanQuijano** [comment]
My student, Carlos Lopez Perez, and I, find a temporal solution.

Go to Repos -> Files And open docker-compose.ci.build.yml file.

Edit and change the image microsoft/aspnetcore:1.0-2.0 by paultrampert/aspnetcore-build-with-yarn

The go to Repos -> Files -> src folder -> MyHealth.Web Folder and open dockerfile file.

Edit and change FROM microsoft/aspnetcore:1.0-2.0 to FROM paultrampert/aspnetcore-build-with-yarn

This image includes the .net core 3.0 sdk and allows the construction of the image necessary to perform both labs.

We hope it helps.

**Comment by carpelo** [comment]
Thanks Juan. It took a while to investigate where was the problem coming
from. I'm glad we worked it out and hopefully it will also help other
students.
Kind regards,
Carlos Pérez López

**Comment by yashints** [comment]
All name changes are here 👉🏽 https://github.com/dotnet/dotnet-docker/issues/2375.

@JuanQuijano shouldn't we stick to official images instead of custom ones?

**Comment by mkennten** [comment]
The issue was fixed with a static, outsourced image - not ideal, but at least the pipelines run again successfully. @krasmuss  Would you like to keep it that way or should we add steps to update to a newer, supported version?
