### ISSUE TITLE
Lab environment - Ubuntu 16.04 will be removed in September, 2021

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#112]
# Module: several
## Lab: several

Description of issue
Ubuntu 16.04 which will be removed September 20, 2021 (see https://github.com/actions/virtual-environments/issues/3287). In some labs pipelines are configured using that version. Labs need to be tested with higher versions and instructions changed.

**Comment by TesterTesterson1004** [comment]
I'm trying to understand this issue a bit better - unfortunately I am not as savvy w/the resources/configs used in AZ-400 as I should be - but in testing one example lab (Module 15) that directly references Ubuntu 16.04 in Exercise 2/Task 1, there is a Step that says:  _"...in the Agent pool dropdown list, select Azure Pipelines and, next, in the Agent Specification dropdown list, select **ubuntu-16.04**..."_

At that point I selected the **ubuntu-18.04** option, and while everything subsequently ran to full success - I noticed in the logs it also referenced the same warning about imminent deprecation of Ubuntu 16.04:

 
![image](https://user-images.githubusercontent.com/49700217/127779189-e7c47f92-7a44-4151-b437-d52bbc50e40f.png)

I poked around to try and find what config option might be able to change that from 16.04 to a newer version, but couldn't find one.  I'm sure I am missing something fairly basic here....does anyone have some insight on what?

**Comment by mkennten** [comment]
Hi, from the screenshot and lab reference I assume this regarding the build pipeline. In fact, the only config change required here is what you have described. In the pipeline config you need to change the used image. When I do this, it works for me:
![image](https://user-images.githubusercontent.com/37703728/128872921-22f54144-5812-445c-82fc-337e1bde810e.png)

![image](https://user-images.githubusercontent.com/37703728/128873093-02cf694f-60ba-4af0-bf9f-4705233a3988.png)

Not sure, what you did differently.

**Comment by LuizMacedo** [comment]
#118 Resolved by updating the Ubuntu version.
