### ISSUE TITLE
Module 19 - Secure DevOps Kit for Azure (AzSK) replaced by Azure Tenant Security Solution (AzTS)

### ISSUE THREAD

**Issue by christiannagel** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#124]
Module 19 describes the *Secure DevOps kit for Azure (AzSK)*. This kit is being phased out in FY21:

[AzSK Sunset Notice](https://github.com/azsk/DevOpsKit-docs/blob/master/ReleaseNotes/AzSKSunsetNotice.md)

In the next version, the **Azure Tenant Security Solution (AzTS)** (developed by the same team) should be referenced instead:

[Azure Tenant Security Solution](https://github.com/azsk/AzTS-docs)

**Comment by unaihuete93** [comment]
Thanks for your help :) This is a Skillpipe/Slideck related issue , which has been reported internally in other channels. GitHub issues should reflect lab instructions related issues.
