### ISSUE TITLE
M08-LAB08: Service Principle Lacks Permissions (or something else)

### ISSUE THREAD

**Issue by AndrewConniff** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#138]
### Contact Details

anconnif@microsoft.com

### What happened?

Exercise : 01
Task: 01
Step: 14

Description of issue:
The deploy step fails on AZ login. The service principle is created

Could be the action has changed.
Could be the Permissions are not valid (AZ credentials (Secrets on GitHub))
Repro steps:
1.
1.
1.

### Lab

Lab 08 Implementing GitHub Actions by using DevOps Starter

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [X] I agree to follow this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
https://github.com/Azure/cli/issues/56
