### ISSUE TITLE
Parallelism in DevOps 

### ISSUE THREAD

**Issue by lexipulsar** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#141]
### What happened?

Hi 😄

I was just wondering how many labs use parallelism? I tried taking the labs 6b & 7 and ran into errors. I'm waiting on access from Microsoft to continue those courses but I'm wondering which ones I can do in the mean time.

Thanks!
Lexi

### Lab

Other

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] I agree to follow this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
hello @lexipulsar, is not really parallelism what labs really need , they need to be able to run private hosted agents. Private hosted agents use to be granted for free (1080 minutes) by default, but it recently changed as mentioned in this blog article: https://devblogs.microsoft.com/devops/change-in-azure-pipelines-grant-for-private-projects/

You can either filling the form in the blog and wait for access, or link an Azure Subscription to the Azure DevOps organization and enable 1 parallel pipeline (which gives unlimited minutes for a single running private agent):
![image](https://user-images.githubusercontent.com/64772417/141138860-75e9f3f1-2531-4546-9c6a-c30496162df2.png)
