### ISSUE TITLE
M07-LAB07: Release pipeline not shown on edit

### ISSUE THREAD

**Issue by christiannagel** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#142]
### Contact Details

christian@christiannagel.com

### What happened?

Exercise : 01  Integrate Azure Key Vault with Azure DevOps
Task: 03 Check the Azure Pipeline
Step: 06 - click the Edit button in the upper right corner

Description of issue:

The pipeline should be shown to continue with step 07. However, the screen is empty.

Repo:
1.  Use the Azure DevOps Demo Generator to generate the Key Vault lab
2. Edit the pipeline

### Lab

Lab 07 Integrating Azure Key Vault with Azure DevOps

### Do you want to help us? 👏

- [X] I agree to follow this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by JuanQuijano** [comment]
We have same issue :(

**Comment by FireyJoe** [comment]
I have run into this too. Testing this as a possible workaround:

1. In releases, export the Current release to JSON
2. Open the document in VS code, format it, and remove the entirety of the Artifacts [] section between lines 293 and 343.
3. Save the file to a new name and re-import it into releases. 
4. Edit the release (this should work now) and re-add the artifacts from the source.

**Comment by prpurand** [comment]
@christiannagel - Validated the issue, its reproducible. @FireyJoe thank you for the work around, it works. I am working on the issue and will update sooner.

**Comment by unaihuete93** [comment]
https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/533

**Comment by aksh-h** [comment]
The reported issue has been resolved by Demo Generator Team.

**Comment by prpurand** [comment]
Validated the changes, there is a yaml suffix added to artifact for classic pipeline output as well. Its a minor string issue. Otherwise, the lab works.. Good to close the issue

![image](https://user-images.githubusercontent.com/69690284/142219350-a9d07b39-cbbe-4ddd-8841-98de2b94150f.png)
