### ISSUE TITLE
M10-LAB10b: can't find this folder and file in repo. Applications\aspnet-core-dotnet-core\Pages\Index.chtml

### ISSUE THREAD

**Issue by vnvbadri** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#144]
### Contact Details

vamsi.badri@spektrasystems.com

### What happened?

Exercise : 01
Task: 02
Step: 02

Description of issue:
Applications\\aspnet-core-dotnet-core\\Pages\\Index.chtml can't find this folder and file in repo.
Repro steps:
1.
1.
1.

### Lab

Lab 10b Creating a Release Dashboard

### Relevant screenshots

paste here 😉
![image](https://user-images.githubusercontent.com/67066769/141355226-dfbad024-e122-4e9d-977a-ed8449145305.png)

### Do you want to help us? 👏

- [X] I agree to follow this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
You may have chosen the wrong Devops Starter template, make sure you choose the **.net core** one. Just tried it myself:
![image](https://user-images.githubusercontent.com/64772417/141467921-217639b2-37d1-4e5e-bdf2-6f26d882bc30.png)
