### ISSUE TITLE
M18-LAB18: TailwindTraders-Website repository doesn't have any branches

### ISSUE THREAD

**Issue by Prasanna-Spektra** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#146]
### Contact Details

prasanna.venkatesh@spektrasystems.com

### What happened?

Exercise : 03
Task: 03
Step: 04

Description of issue:

Initially I have tried to select branch for TailwindTraders-Website repository but it doesn't have any branches then i have created one main branch.

On the Publish code as wiki step, i have set the Folder value to /Documents and Published then i am getting below error.

_**The path '/Documents' either does not exist or is not a folder in version 'main'. Parameter name: mappedPath**_

Repro steps:
1. tried with creating main branch but still no progress

![image](https://user-images.githubusercontent.com/85864326/141467629-3c30ca4b-de77-4757-802c-80431ab3eefc.png)

![r4TgJGk8y0](https://user-images.githubusercontent.com/85864326/141465931-e0775beb-31ac-4ac6-b4ad-1cf1e0135dff.png)
.
![image](https://user-images.githubusercontent.com/85864326/141467975-bc705bea-7f00-4f54-ae67-0a1e3ec0848c.png)

also there are no file in repository after creating the project from template.

### Lab

Lab 18 Integration between Azure DevOps and Teams

### Relevant screenshots

![image](https://user-images.githubusercontent.com/85864326/141466753-2342cc4b-ad45-4329-9583-004993d1a8b1.png)

![image](https://user-images.githubusercontent.com/85864326/141467998-48efcf26-f4e6-4710-b294-5f0df2756695.png)

### Do you want to help us? 👏

- [X] I agree to follow this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by aksh-h** [comment]
Tailwind Traders Template has two repositories, one is Website and another one is Backend. The repository can be seen once the project has been provisioned successfully.

> Website : [Repo](https://github.com/microsoft/tailwindtraders-website)

![image](https://user-images.githubusercontent.com/38463158/142218478-cc7c132c-2e75-4cbe-9289-877de3876b8e.png)


> Backend : [Repo](https://github.com/microsoft/tailwindTraders-Backend)

![image](https://user-images.githubusercontent.com/38463158/142218268-5809beef-017d-43e2-89fb-ed324324dc14.png)

Currently, CI is failing. You can refer to the source repository and raise an issue for the same.
