### ISSUE TITLE
M14-LAB14b: webapp.tf content has changed, provider registration needs to be placed before the resource configuration

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#150]
### What happened?

Exercise : 01
Task: 01
Step: 05

Description of issue:
The snippet for the provider configuration needs to be added after line 9 not 11. If it's added after 11 then it's placed inside the resource configuration and the release pipeline fails.

This is would it would look like following the instructions:
![image](https://user-images.githubusercontent.com/37703728/142447195-e34151aa-690f-4518-b8b4-a85d0460a2ad.png)

This would it should look like:
![image](https://user-images.githubusercontent.com/37703728/142447321-156339c1-fb60-415f-8f77-51908ecea3d2.png)

### Lab

Lab 14b Automating infrastructure deployments in the Cloud with Terraform and Azure Pipelines

### Do you want to help us? 👏

- [X] I agree to follow this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by k21academyuk** [comment]
@mkennten I'm still not able to release the pipeline after changing the file as you suggested. Please help.

Error: 
![2021-11-20 10_37_28-Terraform-CD - Release-7 - Pipelines](https://user-images.githubusercontent.com/69501420/142715196-2f0b8ed4-dbea-43cc-a0bf-ddfc6b6b8717.png)
