### ISSUE TITLE
M01-LAB01: Picture missing

### ISSUE THREAD

**Issue by yashints** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#169]
### Contact Details

yasa@microsoft.com

### What happened?

Exercise : 03
Task: 02
Step: 09

Description of issue: The picture is missing

Repro steps:
1. Launch the lab 
1. Navigate to Lab 01
1. Navigate to Task 2 - Step 9

### Lab

Lab 01 Agile Planning and Portfolio Management with Azure Boards

### Relevant screenshots

<img width="353" alt="Screenshot 2021-11-22 120343" src="https://user-images.githubusercontent.com/13609680/142786875-d3fb8822-cbb0-4c9a-8867-02d97c09fe82.png">

### Do you want to help us? 👏

- [X] I agree to follow this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
looks like the issue is only related to LODS, not being able to render it correctly  using HTML
![image](https://user-images.githubusercontent.com/64772417/142861283-b02499ee-5aa7-4e1e-ad8d-f4b3fe5bf40c.png)
just worried it will look huge with no width limits on GitHub Pages

**Comment by unaihuete93** [comment]
looks like {width} could be used for LODS, but no GitHub Pages https://github.com/LearnOnDemandSystems/docs/blob/master/guides/idl2/idlv2-authoring-guide-and-best-practice.md#embedded-content

**Comment by unaihuete93** [comment]
lets just leave it big, I will approve the PR

**Comment by yashints** [comment]
@unaihuete93 the width is fixed in the LODS anyway (images get %100 from parent element), and students use that most of the time instead of GH pages. I couldn't test it in LODS but there is a way to specify the width using markdown. If you know of a way of testing it, happy to help

**Comment by unaihuete93** [comment]
{width} works for LODS(https://github.com/LearnOnDemandSystems/docs/blob/master/guides/idl2/idlv2-authoring-guide-and-best-practice.md#embedded-content) but not for GitHub Pages (tested it), so lets leave it as proposed :)
