### ISSUE TITLE
M5-LAB05: The instruction is missing a step

### ISSUE THREAD

**Issue by yashints** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#172]
### Contact Details

yasa@microsoft.com

### What happened?

Exercise : 02
Task: 02
Step: 01

Description of issue: The instruction is missing a step which confuses the students

Repro steps:
1. Open lab 5
1. Navigate to Ex 2 - Task 2 - Step 1
1. The step is missing the step to click on the security menu

### Lab

Lab 05 Configuring Agent Pools and Understanding Pipeline Styles

### Relevant screenshots

<img width="839" alt="image" src="https://user-images.githubusercontent.com/13609680/142950856-b63d0456-854d-4122-b2f5-0b37682321a6.png">

### Do you want to help us? 👏

- [X] I agree to follow this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by yashints** [comment]
@unaihuete93 you change to add those bullet points to the Note section looks really off position on GH pages, but I just tested it in the lab and it is OK there 😂, so no change required

**Comment by unaihuete93** [comment]
that is weird, it was looking good on the GitHub markdown rendered version... Before those bullet points were completely out of the comment section
![image](https://user-images.githubusercontent.com/64772417/143546553-3426de1e-f8ae-4d31-a7b8-0f43415c56d0.png)

**Comment by unaihuete93** [comment]
only github pages renders it weird :S 
![image](https://user-images.githubusercontent.com/64772417/143546764-42de26e3-c824-491e-a476-8ef60315741d.png)
