### ISSUE TITLE
M05-LAB05: Cant create Basic yaml because of branch polices

### ISSUE THREAD

**Issue by kobi86** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#175]
### What happened?

Exercise : 01
Task: 01
Step: 06

Description of issue:
Cant push Yaml to the repo because there are branch polices on that repo. 
In order to push the Yaml, we need to disable the branch policy on the project and then we can push the Yaml. 

Repro steps:
1. Create a yaml pipeline 
2. Try to save and commit it to the master branch (Default) 
3. You get branch policy error

### Lab

Lab 05 Configuring Agent Pools and Understanding Pipeline Styles

### Relevant screenshots

paste here 😉

https://snipboard.io/13kUpb.jpg

### Do you want to help us? 👏

- [X] I agree to follow this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
Hello, PartsUnlimited demo generator project does not have any branch protection. Are sure you created a new project or did you reuse the same project from labs 02 or 04?

**Comment by unaihuete93** [comment]
closing until answer received :)

**Comment by kobi86** [comment]
You are right, but now I see another problem :) 
The repo already have an Azure-pipelines.yaml file and in the steps it is asked to create one

**Comment by unaihuete93** [comment]
Good point, maybe modifying the existing Azure-pipelines.yml would be a better approach. We will open the issue as "Feedback" (as the lab works, some students tried it this week, but it could be improved)

**Comment by kobi86** [comment]
@unaihuete93 do you have an Idea how to address this?

**Comment by unaihuete93** [comment]
PR merged to fix it!
