### ISSUE TITLE
M05-LAB: Incorrect Instructions

### ISSUE THREAD

**Issue by ElaMark** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#190]
### Contact Details

mark.walsh.1@outlook.com

### What happened?

Exercise : 01
Task: 01
Step: 13

Description of issue:
Instructions are incorrect.

They should say paste
**trigger:
- main**

### Lab

Lab 05 Configuring Agent Pools and Understanding Pipeline Styles

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by ElaMark** [comment]
Ignore this. Seems that it's a rendering problem in LODS

**Comment by mwjan221** [comment]
The rendering problem is also here: https://microsoftlearning.github.io/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/Instructions/Labs/AZ400_M05_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.html
