### ISSUE TITLE
Lab 09: Unable to sign in to the azure DevOps organization using the provided command

### ISSUE THREAD

**Issue by junnhssn** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#191]
### Contact Details

junnhssn@gmail.com

### What happened?

Lab : 09
Exercise : 01
Task: 02
Step: 18
Unable to sign in to the azure DevOps organization using the provided command 
```
./nuget.exe push -source "PartsUnlimitedShared" -ApiKey AzDO PartsUnlimited.Shared.1.0.0.nupkg
```

After running the above command and entering the credentials, the shell repeatedly asks for the username and password over again until a failure message is displayed. Please guide.

### Lab

Lab 09 Package Management with Azure Artifacts

### Relevant screenshots

![image](https://user-images.githubusercontent.com/47213023/150777490-da2ecc15-9dae-4a1a-b324-c7007b78c421.png)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by mkennten** [comment]
Just my two cents, I did it this week and it worked as expected no issues on my end.
