### ISSUE TITLE
M14-LAB14a: VS Code is not installed on VM

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#202]
### What happened?

Exercise : 01
Task: 06
Step: 03 + 10

Description of issue:
While connected to the VM over SSH from the cloud shell, steps 3 and 10 use "code" to load new_vm_web.yml/myazure_rm.yml, but this executable is not available on the VM.

To fix this, either provide the steps to get VSC installed in the VM or provide a different editor to use in this step.

### Lab

Lab 14a Ansible with Azure

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by kobi86** [comment]
You are right :) 
Already fixed it on [PR #182](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/pull/182)

**Comment by unaihuete93** [comment]
We also need to change the ansible template used to modify from CentOs 7.2(not in marketplace anymore) to 7.4

**Comment by LuizMacedo** [comment]
Fixed #182, thanks @kobi86
