### ISSUE TITLE
LAB14B: Additional instructions request in Lab 14B to avoid project creation errors caused by extensions not  being installed.

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#208]
### What happened?

Exercise : 00
Task: 01
Step: 06

Description of issue:

In Lab 14B (possibly others) we seem to receive a consistent error behavior caused because Extensions are not installed by default, and the existing 'Note' _In case the process fails, navigate to your DevOps organization, delete the project, and try again_ forces students to encounter the error, delete the project, and then have to recreate the project when we may be able to include instructions to proactively avoid it. 

Repro steps:
- I encounter this issue using both DevOps Orgs created using Azure Passes as well as ALH/Cloudslice accounts.
- Note that this error occurs in addition to the error referenced here - https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/issues/207

1. Start Lab 14B, create new Azure DevOps Org.
2. Configure workaround referenced in #207 so as to avoid that issue.
3. Proceed with Task 1 to Step 6, and despite selecting the checkbox we still receive an error on 'Create Project':
![image](https://user-images.githubusercontent.com/49700217/153772922-36059746-a126-48c4-be79-a501423c242c.png)

![image](https://user-images.githubusercontent.com/49700217/153772937-23b33430-9551-4f8b-b198-2c130ff12525.png)

4. If we check our Organization at this point, we will see the project has been created, and both Extensions will be installed. But, since we received an error on the Create Project, does this mean we need to create the project once more?  Even with the error, would the project work if we ran through the steps?
5. Even if the project would work OK at this point, many Students and even Instructors will not like having seen the error and will instead delete the project, and then re-run it so that - now the Extensions are installed - the final project creation attempt will be fully successful:
![image](https://user-images.githubusercontent.com/49700217/153773044-ad4b694b-9118-481c-ace7-16c15ad542c1.png)
![image](https://user-images.githubusercontent.com/49700217/153773125-fd0dd401-872d-4ae7-87af-cad542ef7994.png)

Instead, would it be possible to slightly re-work **Step 6** from this:

1. Back on the **Create New Project** page, if prompted to install a missing extension, select the checkbox below the **Replace Tokens** and **Terraform** labels and click **Create Project**.

To something like this:

1. Back on the **Create New Project** page, if prompted about missing extensions, select the checkbox and then right-click and **Open link in new tab** for both **Replace Tokens** and **Terraform**. In each new browser tab, click the **Get it free** button, click **Install** for your organization, and finally return to your original **Azure DevOps Demo Generator** tab and click **Create Project**.

This would avoid errors + time wasted deleting projects and re-creating them a second time.

 

 

### Lab

Lab 14b Automating infrastructure deployments in the Cloud with Terraform and Azure Pipelines

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by mkennten** [comment]
To answer your question 4: I have had the same error message last week and it tells you that the release pipeline could not be created. So, the tasks in that lab could not be completed. I might have run into the exact same issue that you described, but instead imported on older version of the release pipeline. When I tried the next morning again, the error did not occur. I will watch out for this to happen during this week's training delivery.

**Comment by unaihuete93** [comment]
https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/599

**Comment by unaihuete93** [comment]
issue has been closed in https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/599
