### ISSUE TITLE
M04-LAB08: Failed during build process

### ISSUE THREAD

**Issue by luisdanielse** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#215]
### Contact Details

luisdaniel_se@hotmail.com

### What happened?

Exercise : 01
Task: 01
Step: 15

Description of issue:
The building of the pipeline is failing a provides the following error:
Dotnet command failed with non-zero exit code on the following projects : D:\a\1\s\test\PartsUnlimited.UnitTests\PartsUnlimited.UnitTests.csproj

It is look like the sdk version is no longer supported by any of the Microsoft Hosted Agents.

![image](https://user-images.githubusercontent.com/18663693/157040223-c7a9b02e-86a0-4560-ac5c-8949028408b4.png)

Repro steps:
1.
1.
1.

### Lab

Lab 10a Controlling Deployments using Release Gates

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by Littlebobbytable5** [comment]
I've managed to fix this issue by editing the **PartsUnlimited-CI** pipeline and changing the **Agent Specification** from _windows-2019_ to **_vs2017-win2016_**  
![image](https://user-images.githubusercontent.com/68470613/157344744-c7390bf6-9662-465f-88fe-b8db45f50911.png)

**Comment by kobi86** [comment]
The problem is that _vs2017-win2016_ is deprecated... 
So we must use 2019

**Comment by unaihuete93** [comment]
https://github.com/microsoft/AzureDevOpsDemoGenerator/issues/631

**Comment by unaihuete93** [comment]
fixed! template was updated with chocolatey installation of .net core 2
