### ISSUE TITLE
Lab 10: Feature Flag Management with LaunchDarkly and Azure DevOps: Create project Error.

### ISSUE THREAD

**Issue by JuanQuijano** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#217]
### Contact Details

jc_quijano@hotmail.com

### What happened?

Exercise 0: Configure the lab prerequisites
Task 1: Configure the team project
Step 07: On the Create New Project page, click Navigate to project.

Description of issue:
The Azure Devops Demo Generator return this error:

"Error while creating release definition: Tasks with versions 'LaunchDarkly Rollout:3.*' are not valid for deploy job 'Agent job' in stage Stage 1."

Repro steps:
1. Push button Create Project
1. Open the box whit "Sorry... We ran into an issue" title
1.

### Lab

Lab 10a Controlling Deployments using Release Gates

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
The LaunchDarkly lab and content will be removed from AZ-400. I'm archiving the issue.
