### ISSUE TITLE
M00-LAB00: QUICK_DESCRIPTION

### ISSUE THREAD

**Issue by ushnooo** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#221]
### Contact Details

ushnooo@gmail.com

### What happened?

Exercise : 15
Task: 2
Step: 3

Description of issue:
Build does not work as the project using .net core 3.1

### Lab

Lab 15 Automating infrastructure deployments in the Cloud with Terraform and Azure Pipelines

### Relevant screenshots

![image](https://user-images.githubusercontent.com/5171043/160872512-7a069bc9-0153-4df7-b790-7a0a30062423.png)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
Template now includes choco task for installing the missing .net core 2.0
