### ISSUE TITLE
M07-LAB17: formatting visual studio installation

### ISSUE THREAD

**Issue by mvdiemen** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#222]
### Contact Details

mrtentje@gmail.com

### What happened?

Exercise : Instructions
Step: Review applications required for this lab

Description of issue: the formatting of the selected workloads show still some Markdow. This is not the case in AZ400_M04_Feature_Flag_Management_with_LaunchDarkly_and_Azure_DevOps. So I synced them so they have the same content.

### Lab

Lab 17 Package Management with Azure Artifacts

### Relevant screenshots

![image](https://user-images.githubusercontent.com/1440089/161144464-4b75b00a-0dc9-4824-ab43-bc85976f525f.png)

### Do you want to help us? 👏

- [X] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
it is related to how LODS renders it compared to GitHub Pages. 

the actual syntax is needed for LODS
![image](https://user-images.githubusercontent.com/64772417/165788816-592b25ee-b3a9-428c-98c4-b48797ed16e1.png)

but it does what the issue mentions in GitHub Pages

**Comment by mvdiemen** [comment]
> it is related to how LODS renders it compared to GitHub Pages.
> 
> the actual syntax is needed for LODS ![image](https://user-images.githubusercontent.com/64772417/165788816-592b25ee-b3a9-428c-98c4-b48797ed16e1.png)
> 
> but it does what the issue mentions in GitHub Pages

Strange for me is why it looks ok for this one, since there the same is achieved: https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/Instructions/Labs/AZ400_M04_Feature_Flag_Management_with_LaunchDarkly_and_Azure_DevOps.md

**Comment by unaihuete93** [comment]
I think the problem is LODS systems render each lab in a different way, they use some REGEX expressions for modifying instructions. We will need to sync with them @LuizMacedo

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review did not experience this Issue.

**Comment by unaihuete93** [comment]
We need to sync with LODS to take a decision. Not critical as we may replace this lab

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue
