### ISSUE TITLE
M04-LAB10: LaunchDarkly-CI Build pipeline - Test task fails due Microsoft.NETCore.app, version 2.0.0 was not found

### ISSUE THREAD

**Issue by cdproyect** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#228]
### Contact Details

cdproyect@gmail.com

### What happened?

Exercise : 01
Task: 03
Step: 26

Description of issue:

The pipeline "LaunchDarkly-CI" fails at the Task "Test" because the framework "Microsoft.NETCore.App, version 2.0.0 was not found.

Repro steps:
1. Follow step by step Exercise 1: Configure feature flags in Azure DevOps by using LaunchDarkly 
1. On step 26, when running the pipeline, the Agent job 1, will fail at the Test task as shown on the image below
![Screen Shot 2022-04-07 at 1 17 48 PM](https://user-images.githubusercontent.com/38844319/162260418-e742a782-efe5-4ff9-bb0a-d9bd3991c097.png)

### Lab

Lab 10 Feature Flag Management with LaunchDarkly and Azure DevOps

### Relevant screenshots

![Screen Shot 2022-04-07 at 1 19 57 PM](https://user-images.githubusercontent.com/38844319/162260682-3fb0a343-d3b2-4ba5-ba26-409fa942889d.png)
![Screen Shot 2022-04-07 at 1 17 48 PM](https://user-images.githubusercontent.com/38844319/162260706-91a19005-36ba-45db-a4f8-2a93b7fa1ed5.png)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by cdproyect** [comment]
Here is a work around that helped me to overcome this issue:

1. On your LaunchDarkly project, select "pipelines", then double click on the "LaunchDarkly-CI" pipeline
1. Edit the pipeline by selecting the 3 vertical dots as shown on the image below
![Screen Shot 2022-04-07 at 1 25 58 PM](https://user-images.githubusercontent.com/38844319/162261743-9dadba3f-5c92-4372-9a08-988423df86b3.png)
1. Add a new task of type ==> "Use.Net Core" , using the configuration shown below
![Screen Shot 2022-04-07 at 1 21 39 PM](https://user-images.githubusercontent.com/38844319/162261007-b00ed9b7-9e92-4bbc-b3ce-bf5532409cb0.png)

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review did not experience this Issue.
