### ISSUE TITLE
Lab needs to be updated. It will fail starting at Task 04 Step 03.

### ISSUE THREAD

**Issue by cosminlof** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#23]
# Module: 14
#### Step: 03

Description of issue
Been trying to reproduce the lab, Ansible with Azure, a couple of times now and it failed to be reproduced.
What I've seen, is that if you install ansible using the apt command, subsequent tasks will fail. One, because version 2.5 is installed and it will fail here: "ansible-galaxy collection install azure.azcollection", and if ansible 2.9 is installed via apt command, it will fail at Task 8, Step 10, here: "ansible-playbook ~/PartsUnlimitedMRP/Labfiles/AZ-400T05-ImplemntgAppInfra/Labfiles/ansible/new_vm_web.yml --extra-vars "vmname=<VM_name> resgrp=az400m14l03arg vnet=az400m1403vm1VNET subnet=az400m1403vm1Subnet"".

Also I've changed the default version of python that is used and it worked; but I had to change the version in the commands where python2.7 string was found and replace it with 3.6

It was more troubleshooting than following the steps, but it was an experience. 

Thanks.

**Comment by TesterTesterson1004** [comment]
Hopefully the course owner here can take the helm and identify the authoritative fix soon - I, too, have been unable to make this lab work with the steps given despite multiple run-throughs.

In case cosminlof is still watching this issue report:  do you have any additional notes regarding how you got by the apparent Python 2.7 vs. 3.6 compatibility issues?  

While I was able to get by the error in the 'ansible-galaxy collection install azure.azcollection' step, also by forcing Ansible 2.9, I cannot get any progress past the error when trying to run 'ansible-playbook ~/PartsUnlimitedMRP/Labfiles/AZ-400T05-ImplemntgAppInfra/Labfiles/ansible/new_vm_web.yml --extra-vars "vmname=<VM_name> resgrp=az400m14l03arg vnet=az400m1403vm1VNET subnet=az400m1403vm1Subnet'

It errors differently depending on whether I try and get dependencies installed via either pip, or pip3, but in either case I run the ship hard aground on the reef of this error:

![image](https://user-images.githubusercontent.com/49700217/106932661-da7e3d80-66cc-11eb-8582-3f5944383099.png)

**Comment by ZekeStarr** [comment]
Is there an update on this issue? As-is, the instructions for Mod 14 are non-functional.

**Comment by mkennten** [comment]
This lab has been updated and the issues fixed.

**Comment by luisdanielse** [comment]
I had run this lab in the past without any problem but now I have the following error:

TASK [Create storage account] **********************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error retrieving resource group az400m14l03arg - Could not retrieve token from local cache. Please run 'az login'."}

PLAY RECAP *****************************************************************************************************************************************************************
localhost
