### ISSUE TITLE
M06-LAB15: Terraform:init failed with exit code 1

### ISSUE THREAD

**Issue by rashika-dabas** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#238]
### Contact Details

rashikadabas19@gmail.com

### What happened?

Exercise : 01
Task: 03
Step: 25

Description of issue:
Terraform: init task failed with exit code 1.
Error: The process 'C:\hostedtoolcache\windows\terraform\0.12.3\x64\terraform.exe' failed with exit code 1.
Ultimately, the release failed because of this task.

![image](https://user-images.githubusercontent.com/77570881/164702507-e65e3319-b53d-4300-8a44-8137c761524e.png)

### Lab

Lab 15 Automating infrastructure deployments in the Cloud with Terraform and Azure Pipelines

### Relevant screenshots

![image](https://user-images.githubusercontent.com/77570881/164702574-4e43021b-b8c2-4f34-8f5e-c14e005ff4dd.png)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by rob-foulkrod** [comment]
This is usually because the 'Replace Tokes' step has not been correctly configured. See #236

**Comment by rashika-dabas** [comment]
@rob-foulkrod Thank you! I was stuck on this for the entire week.

**Comment by azureaddeepak** [comment]
Hi Team 
please guide me how to resolve the issue , error showing is : the process 'c:\hostedtoolcache\windows\terraform\0.12.3\x64\terraform.exe' failed with exit code 1

**Comment by petender** [comment]
@azureaddeepak could you validate if this helps/helped in your case? https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/issues/236
