### ISSUE TITLE
M08-LAB19: EXTERNAL-IP not opening in web browser

### ISSUE THREAD

**Issue by rashika-dabas** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#245]
### Contact Details

rashikadabas19@gmail.com

### What happened?

Exercise : 00
Task: 00

Exercise: 01 Task: 03 Step: 14

Description of issue: 
Ip-address in the EXTERNAL-IP column not opening MyHealthClinic application in the web browser because the traffic is not being redirected to the node and so the website says "This site can’t be reached" due to connection timeout.

Repro steps:
Add steps to implement ingress as task 4 to open the application.

### Lab

Lab 19 Deploying a multi-container application to Azure Kubernetes Services

### Relevant screenshots

![browse](https://user-images.githubusercontent.com/77570881/165621758-b8eb99d6-c4a7-428b-8e3c-dd6c67e432f1.png)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
Lab worked for my attendees from last week. Make sure you replace the variables correctly on the CI pipeline. Looks like your pod is crashing, you can review from azure portal. Closing issue.
