### ISSUE TITLE
Lab 11b: IIS Web App Manage fails with error Process 'appcmd.exe' exited with code '5' - Cannot read configuration file due to insufficient permissions

### ISSUE THREAD

**Issue by Simran-99** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#246]
### What happened?

Exercise : 01
Task: 03
Step: 02

Description of issue: Not able to run the release pipeline

Repro steps:
1.
1.
1.

### Lab

Lab 13 Setting Up and Running Functional Tests

### Relevant screenshots

![Capture](https://user-images.githubusercontent.com/68385902/165629473-3fe09c38-85cf-43b1-85cc-b7a4b084fc65.PNG)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
@unaihuete93 are you seeing this issue recently? Otherwise, this lab will probably be replaced by Playwright https://docs.microsoft.com/en-us/microsoft-edge/playwright.

**Comment by unaihuete93** [comment]
I have not tried this lab in a long time, as you mentioned, it should be replaced/renewed.

**Comment by LuizMacedo** [comment]
Closing as the lab will be replaced soon. Thanks.
