### ISSUE TITLE
LAB01: Fix Work Item name references

### ISSUE THREAD

**Issue by JBrunskowski** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#251]
### Contact Details

jason.brunskowski@gmail.com

### What happened?

Exercise : 01
Task: 03
Step: 03, 04, 10, 11

Description of issue:
There is a step to create a Work Item with the title of **_Add page for most recent tutorials_**. However, subsequent references to this Work Item call it **_Add page for most recent tutorial_** - without the "s"

### Lab

Lab 01 Agile Planning and Portfolio Management with Azure Boards

### Relevant screenshots

![image](https://user-images.githubusercontent.com/18314734/165999883-8eb7deef-55e3-4411-9bdf-57ad14ebb697.png)

![image](https://user-images.githubusercontent.com/18314734/165999931-cd94c77b-6994-411c-9fdf-126c43a9277a.png)

![image](https://user-images.githubusercontent.com/18314734/165999981-86d3a504-5a5e-48f2-a233-3e5ade64d910.png)

### Do you want to help us? 👏

- [x] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by JBrunskowski** [comment]
Pending Pull Request is [here](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/pull/250).

**Comment by unaihuete93** [comment]
Thank you :)
