### ISSUE TITLE
 Failed Requests alert condition not found in the Azure dashboard.

### ISSUE THREAD

**Issue by JossyWalston88** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#254]
### What happened?

Exercise : 00
Task: 03
Step: 14

Description of issue:
 "Failed Requests" signal not found in azure dashboard.

Repro steps:
1.
1.
1.

### Lab

Lab 08 Controlling Deployments using Release Gates

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
Make sure Application Insights > Alerts is selected, not App Service Alerts. It happened to many of attendees in the past.

**Comment by JossyWalston88** [comment]
Thank you so much.
