### ISSUE TITLE
In all Release pipelines, Azure resources not auto populating after selecting the Azure Pass sponsorship.

### ISSUE THREAD

**Issue by azurearchitect786** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#255]
### Contact Details

azurearchitect8@gmail.com

### What happened?

In All release pipelines, after we select the Azure Pass Sponsorship, the azure resources deployed for release are not auto populating.

Various participants including I (MCT), encountered the same issue multiple times.

Screenshots attached

Thanks

### Lab

Lab 08 Controlling Deployments using Release Gates

### Relevant screenshots

![image](https://user-images.githubusercontent.com/56661030/170636305-62726346-7eea-4f0a-a201-6e1ed3db0e38.png)
![image](https://user-images.githubusercontent.com/56661030/170636335-b4a064be-2351-4063-bb2a-2c87bc06b4a4.png)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by tiagocostapt** [comment]
That's common to happen to me too. My advice is just to type the name of the webapp on the combo box, and follow the rest of the instructions. It will work. If you wait for a long time, it will start to show on the box. I never had time to measure the exact time, but i tried to reset the cache, auth tokens etc.. and nothing seems to work. Would love to see if other MCTs have some other ideas. @petender any idea on this?

**Comment by petender** [comment]
How silly as it seems, I've seen this related to screen resolution or how much "space" the graphical section to the right has. It seems to be related to the Javascript engine that's building the ADO web pages. If you try to make that GUI column to the right a bit wider, it seems to be fixed most of the time... Not a solid solution, just sharing what does it for me. FYI, it's not related to AzurePass, have seen the same on Corp subscriptions or Trial ones. (Same comes up with some other labs like the Canary/Prod and Keyvault lists that need to populate)

**Comment by tiagocostapt** [comment]
I will try that next time @petender ! Great tip. Never thought about that. I have an 4k 28'' screen and never had the issue, that might be the reason. Still silly for that to happen but it's what it is.

**Comment by unaihuete93** [comment]
As mentioned in the thread, my experience has been the same, no matter the susbcription type used. Either try typing the resource or play with bigger resolutions. We need to close the issue, as it is not related to the lab instructions, it is a general issue related to Azure DevOps. You can report it at: https://developercommunity.visualstudio.com/report?space=21&entry=problem
