### ISSUE TITLE
M00-LAB03: Duplicate instructions

### ISSUE THREAD

**Issue by Tattedgeek** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#264]
### Contact Details

brent.dawson@gmail.com

### What happened?

Exercise : 01
Task: 00
Step: 00

Description of issue: Duplicate instructions

The entire first exercise of the lab is the same as in lab 2. This can't be repeated and a note should be made that it's a continuation from the previous lab.

### Lab

Lab 03 Version controlling with Git in Azure Repos

### Relevant screenshots

The entire first exercise of the lab is the same as in lab 2. This can't be repeated and a note should be made that it's a continuation from the previous lab.

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
each lab is designed to be completely independent. 

On this one, there is a warning if you want to make it a continuation on previous one: 
![image](https://user-images.githubusercontent.com/64772417/175109494-f4a874a4-03dd-4492-b21a-feccbb990a7a.png)
