### ISSUE TITLE
LAB01:Explore Git branch model for continuous delivery

### ISSUE THREAD

**Issue by eliassal** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#265]
### Contact Details

salamadmin@free.fr

### What happened?

Exercise : Explore Git branch model for continuous delivery
Task: Getting ready
Step: We'll be using the myWebApp created in the previous exercises

Description of issue: It is indicated " We'll be using the myWebApp created in the previous exercises...", where are those exercises or can you point me to where I can find the steps to setup the environment for myWebApp in this learning path

Repro steps:
1. Go to 
https://docs.microsoft.com/en-us/learn/modules/manage-git-branches-workflows/4-explore-git-branch-model-for-continuous-delivery

### Lab

Lab 00 Validate lab environment

### Relevant screenshots

paste here 😉
![image](https://user-images.githubusercontent.com/8447864/176645845-07d3ab98-a3d9-4839-8add-1b4004ddb92f.png)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
This is a Learn content issue, not lab specific. I'll work to fix Learn to point to the requirement.
