### ISSUE TITLE
Lab 06: Integrating External Source Control with Azure Pipelines

### ISSUE THREAD

**Issue by eliassal** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#266]
### Contact Details

salamadmin@free.fr

### What happened?

Exercise : Lab 06: Integrating External Source Control with Azure Pipelines
Task: 4
Step: 6

Description of issue: In this step 6, it is indicated "Create a new branch, set its name to addition-cleanup" which effectively triers a build run in Azure Devops whereas the pipeline trier indicates only master branch as follows

> trigger:
> - master

 Is this a bug or there is a config that allows this  that we are not aware of?
Thanks

Repro steps:
1.follow steps task 4 until step 6
1.
1.

### Lab

Lab 06 Integrating external source control with Azure Pipelines

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by TobiasBreuer** [comment]
Please note that the build is not triggered for the new branch and also not just after any new branch is created.
After performing the changes in the new branch, you have to open a new pull request from the new cleanup branch into the master branch. Once the PR is created, it will take some seconds for the pipeline to be triggered. And it will be triggered, as the PR you just opened *would* affect the **master** branch. So the trigger definition as-is, is enough to also support PR automation.

**Comment by eliassal** [comment]
Hi Tobias, not sure I understand the response as it does not aligh with what is written and happens when creating the new branch in the lab. It is indicated 

> On the Open a pull request page, click Create pull request to initiate the process of getting your untested changes into production code.
> 
> Note: **Azure DevOps will detect the change and start the build pipeline.** This will result in failed checks, triggering an update the GitHub UI.

which in fact triggered the pipeline

**Comment by LuizMacedo** [comment]
I am closing the issue for now. The lab will be refreshed soon.
