### ISSUE TITLE
Lab 08: Deploying Docker containers to Azure App

### ISSUE THREAD

**Issue by eliassal** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#268]
### Contact Details

salamadmin@free.fr

### What happened?

Exercise : 02
Task: 02
Step: 13

Description of issue: When I click the URL link entry representing the target web app, I get the following error
![Lab08-err](https://user-images.githubusercontent.com/8447864/177789917-294f73e9-784e-4a2a-b772-86c499b2f369.jpg)

I switched to diagnostics but it does not help very much, can you please let me know how to investigate as I am new to this type of applications/platform
![Lab08-err_Diag](https://user-images.githubusercontent.com/8447864/177789945-5fb42eea-baad-4ad0-bed1-512dba3a6331.jpg)

Thanks in advance

Repro steps:
1. Follow instructions until the mentioned task
1.
1.

### Lab

Lab 08 Deploying Docker Containers to Azure App Service web apps

### Relevant screenshots

![image](https://user-images.githubusercontent.com/8447864/177790043-8ff4e3ba-1d61-49de-9377-7251d09621a4.png)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
Hello @eliassal , my students did not have any problem this week with the lab. Most probably from the screenshot I believe the connectionString on the webapp configuration may be wrong (and app fails to start).
