### ISSUE TITLE
Lab 13: Integrating Azure Key Vault with Azure DevOps : The release pipeline is failing 

### ISSUE THREAD

**Issue by junnhssn** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#269]
### Contact Details

junnhssn@gmail.com

### What happened?

Exercise 1: Integrate Azure Key Vault with Azure DevOps
Task 3: Check the Azure Pipeline
Step: 21
Description of issue:
The release pipeline is failing with the following error message. 
“Error: Resource 'hotel-coupon-mgmt29e2de9b' doesn't exist. Resource should exist before deployment.”
Correct me if I am wrong, we are deploying the web app as part of the release pipeline and the web app is successfully deployed.

Not sure what I'm doing wrong. Followed all the steps to the dot. Please assist. Thanks. 

### Lab

Lab 13 Integrate Azure Key Vault with Azure DevOps

### Relevant screenshots

Error message
![image](https://user-images.githubusercontent.com/47213023/178021217-f5e597f9-f4fd-4388-bad0-964470132331.png)
![image](https://user-images.githubusercontent.com/47213023/178021225-244f3ecc-58a0-4bad-82f5-5df7aae1e187.png)

The deployment of Web app
![image](https://user-images.githubusercontent.com/47213023/178021234-8314f38e-77f8-4e54-82ee-dece3ffd01f7.png)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by junnhssn** [comment]
@[LuizMacedo](https://github.com/LuizMacedo) Could you please help us out here? Thanks.

**Comment by unaihuete93** [comment]
we may be able to help if task details are shown (pipeline definition)
