### ISSUE TITLE
LAB10: Unable to Create a Release Dashboard

### ISSUE THREAD

**Issue by wralex** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#271]
### Contact Details

wralex@gmail.com

### What happened?

Exercise : 10
Task: 01
Step: 09

Description of issue:

Failed at Module 4, Task 1, Step 5 and receive the following:

```json
{
    "status": "Failed",
    "error": {
        "code": "ProjectNotFoundWithId",
        "target": "GetAzurePipelineOperation",
        "message": "Failed to create Azure Pipeline 'Creating a Release Dashboard'. More details: 'Configuration failed at step: 'Configuring build pipeline'. More details: Specified argument was out of the range of valid values.\r\nParameter name: JobAuthorizationScope.'. "
}
```

I'm unable to continue.

### Lab

Lab 10 Creating a release dashboard

### Relevant screenshots

![image](https://user-images.githubusercontent.com/1946786/179835195-367e2ca0-e255-47fa-a8ed-cab2cbd14718.png)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
this lab will be retired soon, have not used it myself in a long time :(

**Comment by LuizMacedo** [comment]
I am closing the issue. As pointed out by @unaihuete93, the lab will be retired in our next refresh.
