### ISSUE TITLE
M09-LAB18: Azure CLI throws an error during WebApp creation

### ISSUE THREAD

**Issue by massimobonanni** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#276]
### Contact Details

massimo.bonanni@tiscali.it

### What happened?

Exercise : 00
Task: 02
Step: 06

Description of issue:
When the student runs the command "az webapp create....", the CLI throws the error shows in the attached screenshot.
The error happened for all the students in my course.

### Lab

Lab 18 Monitoring application performance with Application Insights

### Relevant screenshots

![Web capture_28-7-2022_14419_labclient labondemand com](https://user-images.githubusercontent.com/9560142/181508658-41130867-493c-4344-b4ff-6116c688ce6e.jpeg)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
Hello @massimobonanni ,

the problem thgy probably execute the "az extension" commands, without reading the note above. I think we should delete the note and 2 commands, they create more confusion (rather than helping)

**Comment by unaihuete93** [comment]
if you have time to create a PR deleting the Note and two "az extension" commands, I will approve it ASAP ;)
