### ISSUE TITLE
M05-LAB13: Deployment fails at the end of task 3

### ISSUE THREAD

**Issue by Kiyani1** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#284]
### What happened?

Exercise: 01
Task: 03
Step: 20

Description of issue:
Deployment fails with the error "template deployment is not valid according to the validation procedure".
Repro steps:
1. Complete all tasks till task 3 step 20
2. Deployment fails 

### Lab

Lab 13 Integrate Azure Key Vault with Azure DevOps

### Relevant screenshots

![image](https://user-images.githubusercontent.com/98971092/187980164-0d14619b-4453-494d-9b38-fea9be57d899.png)

Please excuse the incorrect numbering in the lab steps. The steps are same as GitHub.

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by erikvanappeldoorn** [comment]
I had the similar issue, any suggestions on this one?

**Comment by LuizMacedo** [comment]
@petender @unaihuete93, are you seeing this issue recently?

**Comment by petender** [comment]
Just tested it this afternoon. Apparently, the issue seems related to the Build Agent reference still being Ubuntu 18.04, where it should be **Ubuntu 20.04** - following the exact guidelines, I got the exact same error, where once updating to the latest Ubuntu version, deployment ran successfully. 
![Uploading 2022-09-02_16-00-48.jpg…]()

**Comment by petender** [comment]
![2022-09-02_15-59-31](https://user-images.githubusercontent.com/62486122/188244619-e829337e-570b-4f3e-8530-21409d86d74f.jpg)

**Comment by Kiyani1** [comment]
Verified, that all resources were deployed successfully.

Thank you all.
