### ISSUE TITLE
M07-LAB15: Steps to activate Mend are not updated as per UI

### ISSUE THREAD

**Issue by Kiyani1** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#287]
### What should we change?

Under Exercise 1 Task 1 steps to activate Mend need to be updated as per the new UI, Mend is now available under Extensions in organization settings.

### Lab

Lab 15 Implement security and compliance in Azure DevOps Pipelines

### Relevant screenshots

![image](https://user-images.githubusercontent.com/98971092/188475105-8669f9dd-72a5-4c5b-ad83-77c99c4977cc.png)

**Comment by unaihuete93** [comment]
@Kiyani1 lab will be updated soon, it will be YAML based and using the new extension.

**Comment by Kiyani1** [comment]
> @Kiyani1 lab will be updated soon, it will be YAML based and using the new extension.
Any ETA on the lab update?

**Comment by LuizMacedo** [comment]
@Kiyani1 it's under review #297 and will be updated soon. I am closing the issue since it's resolved in our next update.
