### ISSUE TITLE
Lab 13 creation of access policy

### ISSUE THREAD

**Issue by MaratMussabekov** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#290]
### Contact Details

marat.4f@gmail.com

### What happened?

Exercise : 01
Task: 02
Step: 04

Description of issue:

Hello team, the key vault access policy creation process looks outdated. Currently, the creation steps are different.
Thank you

### Lab

Lab 13 Integrate Azure Key Vault with Azure DevOps

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
I am closing the issue. We are in the process of refreshing this lab. Thank you.
