### ISSUE TITLE
AZ400_M07_L15_Implement_Security_and_Compliance_in_an_Azure_Pipeline.md

### ISSUE THREAD

**Issue by JuanQuijano** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#291]
### Contact Details

jc_quijano@hotmail.com

### What happened?

Exercise : 01
Task: 01
Step: 01

Description of issue:
* The Mend Bolt extension is no longer installed automatically from the azuredevopsgenerator, it must be installed from the marketplace, in its free version.

* The Ment Bolt options to enter the data to activate the free account no longer appear there.
Now it appears in the configuration of the organization, at the bottom of the vertical menu on the left.

### Lab

Lab 15 Implement security and compliance in Azure DevOps Pipelines

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by az400raf** [comment]
Time passed and the students still have an invalid lab

**Comment by unaihuete93** [comment]
the update will be released in December, you can see the updates coming here #297
