### ISSUE TITLE
M04-LAB09: delete unnecessary "continous monitoring task" 

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#293]
### What happened?

Exercise : 00
Task: 00
Step: 00

Description of issue:

Repro steps:
1.  it keeps asking for APP insights dropdown if no deleted 
1.
1.

### Lab

Lab 09 Control Deployments using Release Gates

### Relevant screenshots

![image](https://user-images.githubusercontent.com/64772417/192543569-e2ff5273-2499-415a-92bd-5fdf5d3c19f5.png)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
Lab refreshed and using YAML instead of Classic.
