### ISSUE TITLE
M05-LAB13: Instructions deviate from UI

### ISSUE THREAD

**Issue by AndrewConniff** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#295]
### What happened?

Exercise : 01
Task: 02
Step: 04

Description of issue:

Repro steps:
1. When getting to this step the "Add Access Policy" is now '+ Create'
1. The select none option is not available, user must select permissions
1. The next section then allows user to finish as you would expect need the instructions prior to the 'reviiew and Create' then 'create' steps.

Thanks

### Lab

Lab 13 Integrate Azure Key Vault with Azure DevOps

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
this PR will renew lab #303

**Comment by az400raf** [comment]
3 weeks after, the bug is still present

**Comment by unaihuete93** [comment]
Lot of labs will be renewed/published in December. If you cannot wait take a look at the opened PRs , #303 for this one.
