### ISSUE TITLE
M04-LAB09: The name of the application insights cannot be viewed 

### ISSUE THREAD

**Issue by shashankms9** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#296]
### Contact Details

msshashank1997@gmail.com

### What happened?

Exercise: 01 Configure release pipeline
Task: 01 Update release tasks
Step: 09

Description of issue: not able to view the **Application Insights resource name** dropdown list, has created the **application insights** resource already.

### Lab

Lab 09 Control Deployments using Release Gates

### Relevant screenshots

![image](https://user-images.githubusercontent.com/104433795/192978493-a2131488-86ea-4aa5-91ed-b80df29f2e61.png)
![image](https://user-images.githubusercontent.com/104433795/192979250-87fa53c1-eade-4d70-82d9-686eecde91e4.png)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by renaudwangler** [comment]
Did you wait long enough ? I had the same problem but the name finally appeared after a (long) time....
