### ISSUE TITLE
M00-LAB14: VM size is unavailable in Azure

### ISSUE THREAD

**Issue by MaratMussabekov** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#299]
### What should we change?

PROPOSAL

### Lab

Lab 14 Azure deployments using Azure Resource Manager templates

### Relevant screenshots

Hello team,
ARM template that is used in the lab contains following:
```
 "vmSize": {
        "type": "string",
        "defaultValue": "Standard_D2s_v5",
        "metadata": {
          "description": "Size of the virtual machine."
        }
```
This VM size causes error "Operation could not be completed as it results in exceeding approved standardDSv5Family Cores quota." as this VM size is unavailable for most of the Azure regions. I would recommend to change it to "Standard_D2s_v4", which is available everywhere.
Thank you

**Comment by LuizMacedo** [comment]
Fixed.
