### ISSUE TITLE
Lab 06: Integrating External Source Control with Azure Pipelines Student lab manual

### ISSUE THREAD

**Issue by Saikishorkhadge** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#304]
### Contact Details

saikishorkhadge@gmail.com

### What happened?

Exercise : 03
Task: 04
Step: 07

Description of issue:
I couldn't see all checks failed

Repro steps:
1.
1.
1.

### Lab

Lab 06 Integrating external source control with Azure Pipelines

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
It should be fixed now. I am closing the issue for now. Feel free to reopen it if you still have any problems. Thanks.
