### ISSUE TITLE
M00-LAB10: Instructions is different from azure portal.

### ISSUE THREAD

**Issue by v-asamim** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#306]
### What should we change?

Description of issue
Instructions and azure portal are different, Instructions docs needs some updating.

Repro steps:

Exercise 1, Task 1, Step 8 -> 
 
1. Server name,
2. Enter username, 
3. Location, 
4. Database name

 from instructions are not in the azure portal.

### Lab

Lab 10 Creating a release dashboard

### Relevant screenshots

![image](https://user-images.githubusercontent.com/111972688/198305668-12830114-beab-4c25-9540-19f2f463d3bc.png)

**Comment by unaihuete93** [comment]
@LuizMacedo @petender we should delete this lab, DevOps Starter will get retired in March

**Comment by unaihuete93** [comment]
#372

**Comment by LuizMacedo** [comment]
Closing this issue since the lab is now deprecated by #422. Thanks!
