### ISSUE TITLE
M00-LAB13: Instructions need some updates

### ISSUE THREAD

**Issue by v-asamim** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#307]
### What should we change?

Description of issue
Instructions and azure portal are different, Instructions docs needs some updating.

Repro steps:

1. Exercise 1, Task 2, Step 4 -> "+ Add Access Policy" from instructions should change to "+ Create"
2. Exercise 1, Task 2, Steps 5, 7 -> "Add access policy" from instructions should change to "Create an access policy"
3. Exercise 1, Task 2, Step 10 -> Secrets is not under Settings section, it's under Objects section.

### Lab

Lab 13 Integrate Azure Key Vault with Azure DevOps

### Relevant screenshots

**Exercise 1, Task 2, Step 4,5,7**
![image](https://user-images.githubusercontent.com/111972688/198315054-9604b984-7862-47ca-a880-01da66315cae.png)

 **Exercise 1, Task 2, Step 10**
![image](https://user-images.githubusercontent.com/111972688/198321417-938a8957-c517-4ba8-b5ca-08090a557b95.png)

**Comment by unaihuete93** [comment]
#303 will fix it
