### ISSUE TITLE
M00-LAB12: Instructions links does not open inside of VM

### ISSUE THREAD

**Issue by v-asamim** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#308]
### What happened?

Exercise: 00
Task: 02
Step: 01

Description of issue:
Instructions links does not open inside of VM, its opening inside main computer browser.

Repro steps:
1. Exercise 0, Task 2, Step 1 -> "Deploy to Azure" link does not open inside of VM, its opening in computer browser.

### Lab

Lab 12 Setting up and running functional tests

### Relevant screenshots

![image](https://user-images.githubusercontent.com/111972688/198642385-46a76270-c675-42cf-b38a-ef4cb919313e.png)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
It should be fixed now. Thank you.
