### ISSUE TITLE
M00-LAB15: An error message was found while running the pipeline.

### ISSUE THREAD

**Issue by v-asamim** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#309]
### What happened?

Exercise: 01
Task: 01,02
Step: 01

Description of issue:
Instructions and azure portal are different.
An error message was found while running the pipeline.

Repro steps:
1. Exercise 1, Task 1, Step 1 -> "Mend Bolt" is not found on the azure portal.
2. Exercise 1, Task 2, Step 1 -> An error message was found while running the pipeline.

### Lab

Lab 15 Implement security and compliance in Azure DevOps Pipelines

### Relevant screenshots

**Exercise 1, Task 1, Step 1**
![image](https://user-images.githubusercontent.com/111972688/198663782-ec71e352-5905-4bae-b4d8-66498c2d86bb.png)

**Exercise 1, Task 2, Step 1**
![image](https://user-images.githubusercontent.com/111972688/198664093-fe2868b1-40e1-4e76-a126-49b4fcc136a4.png)
![image](https://user-images.githubusercontent.com/111972688/198664162-b185c52a-3c57-41f9-9797-595919a8c270.png)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
@LuizMacedo should we fix it or wait for the lab renewal to be published?
