### ISSUE TITLE
M00-LAB16: An error message was found while running the pipeline YAML (SonarCloud)

### ISSUE THREAD

**Issue by v-asamim** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#310]
### What happened?

Exercise: 01
Task: 02
Step: 08

Description of issue:
An error message was found while running the pipeline YAML.

Repro steps:
1. Exercise 1, Task 2, Step 8 ->An error message was found while running the pipeline YAML.
  Error message: "There was a resource authorization issue"

### Lab

Lab 16 Managing technical debt with SonarQube and Azure DevOps

### Relevant screenshots

![image](https://user-images.githubusercontent.com/111972688/198667941-511ab3a4-361f-4f5f-a0f9-bae2af584b64.png)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by az400raf** [comment]
I have the same error. The project's service connection list is empty.
The reason of the failure is that in the lab manual those steps are not described in detail. After adding the service connection like described on the Sonar web page, it started working

![image](https://user-images.githubusercontent.com/118273632/202192769-6f5805fd-75e6-4005-947b-c625ce65ec25.png)

After that the pipeline fails anyway with the error:
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/118273632/202193656-9c4fba14-f2c6-4d15-9912-ac54a15dff59.png">

**Comment by unaihuete93** [comment]
these are not the same issue:

- @v-asamim has a wrongly named service connection in the pipeline
- @az400raf your problem is the build task not finding the correct .NET project in the repository. Need more information to identity (paste pipeline+build task details)

**Comment by LuizMacedo** [comment]
I am closing the issue, for now. Feel free to reopen after check the suggestions provided. Thanks.
