### ISSUE TITLE
M04-LAB10: DevOps Starter cannot be created

### ISSUE THREAD

**Issue by az400raf** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#317]
### Contact Details

az400raf@outlook.com

### What happened?

Exercise : 01
Task: 01
Step: 09

Description of issue:
After filling up the form with the described values, the DevOps Starter is not created and no error message is displayed. There are also some limitations in place:
1 - A message is displayed: DevOps starter is being deprecated and will get retired on March 31, 2023.
2 - By default a database server is going to be created in Australia region, but this location is not allowed by the Azure Pass - Sponsorship subscription

Repro steps:
1. Do all the steps using an Azure Pass - Sponsorship subscription. This step number 9 is not going to do anything.
2. I tried to change the location to another region like "Central US" - it does not help.

### Lab

Lab 10 Creating a release dashboard

### Relevant screenshots

<img width="620" alt="image" src="https://user-images.githubusercontent.com/118273632/202116708-1ccb5f9c-3291-4389-b54a-3f9d2ce88ae5.png">

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by az400raf** [comment]
I tried again after some hours and it was finally built. That must be a kind of a problem on Azure side, as the attached web page was just open in the browser a few hours. Before closing it I tried to click once again the "Create" button and this time it worked. I suggest to close the issue

**Comment by unaihuete93** [comment]
lab will be replaced, as tool is getting deprecated
