### ISSUE TITLE
M05-LAB12: VM Size not available

### ISSUE THREAD

**Issue by az400raf** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#318]
### Contact Details

az400raf@outlook.com

### What happened?

Exercise : 00
Task: 02
Step: 06

Description of issue:
At the final step  where the machine should be created an error is shown:
{"code":"InvalidTemplateDeployment","details":[{"code":"SkuNotAvailable","message":"The requested VM size for resource 'Following SKUs have failed for Capacity Restrictions: Standard_D2_v2' is currently not available in location 'centralus'. Please try another size or deploy to a different location or different zone. See https://aka.ms/azureskunotavailable for details."}],"message":"The template deployment 'Microsoft.Template-20221116094628' is not valid according to the validation procedure. The tracking id is 'b5fc3333-1148-46c0-bdf9-f005abc606ed'. See inner errors for details."}

Repro steps:
1. Just follow with the steps of the lab

Workaround: 
After step 4 replace also:
"vmSize": "Standard_D2_v2"
to 
"vmSize": "Standard_D2s_v3"

and deploy to EastUS location. This should be mentioned in the step where the resource group is created, as the location of the VM is inherited from there

Unfortunatelly after that change the deployment fails with error:
Deployment 'Microsoft.Template-20221116095739' could not be found. (Code: DeploymentNotFound)

### Lab

Lab 12 Setting up and running functional tests

### Relevant screenshots

<img width="860" alt="image" src="https://user-images.githubusercontent.com/118273632/202135590-9823b677-ec3a-4d60-9a32-396cbe640b6d.png">

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
Fixed. Thanks.
