### ISSUE TITLE
M07-LAB17: Authorization error

### ISSUE THREAD

**Issue by az400raf** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#319]
### Contact Details

az400raf@outlook.com

### What happened?

Exercise : 00
Task: 02
Step: 05

Description of issue:
After sigining in using my ...@outlook.com account to Visual Studio (that's the same account as the owner of DevOps organization), I receive error You are not authorized to access <link to organization>

Repro steps:
1. Follow the lab steps on a VM provided during the authorized AZ-400 training

The issue may have something in common with expired license of VS Studio 2019?

### Lab

Lab 17 Package management with Azure Artifacts

### Relevant screenshots

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/118273632/202201038-e2558015-9591-485e-84b3-0b81c21a1071.png">  

Please note, that it seems, that I have already been authenticated in the VS - the icon with my credentials is displayed

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
Is a Visual Studio issue when cloning repo or login to ADO. You need to re-login using Team Explorer on Visual Studio https://learn.microsoft.com/en-us/visualstudio/ide/connect-team-project?view=vs-2019
