### ISSUE TITLE
M09-LAB18: No hosted parallelism has ben purchased or granted

### ISSUE THREAD

**Issue by az400raf** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#320]
### Contact Details

az400raf@outlook.com

### What happened?

Exercise : 01
Task: 01
Step: 17-25

Description of issue:
In step 17 we trigger release by change in the file. We are not supposed for the result, but... in step 25, we are going to check the result of the buid. It failed with an error:

#[error]No hosted parallelism has been purchased or granted. To request a free parallelism grant, please fill out the following form https://aka.ms/azpipelines-parallelism-request

I suppose it is not the goal of the lab

Repro steps:
1. Follow steps of the lab manual

### Lab

Lab 18 Monitoring application performance with Application Insights

### Relevant screenshots

<img width="948" alt="image" src="https://user-images.githubusercontent.com/118273632/202214826-6927f7f3-143c-4260-ad34-eee5cc5060bd.png">
<img width="747" alt="image" src="https://user-images.githubusercontent.com/118273632/202214923-1f900460-5fe1-4f9f-bb59-586a45801e29.png">

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
Make sure you followed Lab 00 https://microsoftlearning.github.io/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/Instructions/Labs/AZ400_M00_Validate_lab_environment.html
You need to have a subscription linked to the ADO org and pay for hosted pipelines
