### ISSUE TITLE
Lab: Sharing Team Knowledge using Azure Project Wikis instructions unclear

### ISSUE THREAD

**Issue by MrPeanutButta** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#33]
# Module: 03
#### Step: 03

Description of issue
==

Azure DevOps does not default to the TailwindTraders-Website repo. Instructions need to make sure to mention selecting the correct repo to find the WebSite.png file.

```
Task 1: Step 3: To the left of the Files pane, in the listing of the repo folder and file hierarchy, expand 
the Documents folder and its Images subfolder, in the Images subfolder, locate the Website.png 
entry, hover with the mouse pointer over its right end to reveal the vertical ellipsis symbol 
representing the More menu, click More, and, in the dropdown menu, click Download to 
download the Website.png file to the local Downloads folder on your lab computer.
```

Repro steps:

1. Visit demo generator and create a Tailwind Traders project.
2. Navigate to Azure DevOps and follow lab instructions.

**Comment by mkennten** [comment]
Thanks for the comment. The lab instruction were clarified using PR #21 which was approved and merge today. That PR was addressing all your topics.
