### ISSUE TITLE
M03-LAB08: Rewrite Lab

### ISSUE THREAD

**Issue by fimdim** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#332]
### What should we change?

- Use eShopOnWeb instead of Azure DevOps Demo Generator.
- Automate infrastructure deployment using Bicep

### Lab

Lab 08 Deploying Docker Containers to Azure App Service web apps

**Comment by LuizMacedo** [comment]
Fixed by #333. Thanks!
