### ISSUE TITLE
M07-LAB16: Link Broken from MS Learn

### ISSUE THREAD

**Issue by k-byun** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#336]
### What happened?

Module: Implement Security and Compliance in an Azure Pipeline
Unit: 9 of 11

### Description of issue:
<kbd>Launch Exercise</kbd> from the learning module is broken.

### Repro steps:
1. From the learning module - unit 9 of 11 - [Implement Security and Compliance in an Azure Pipeline](https://learn.microsoft.com/en-us/training/modules/software-composition-analysis/9-implement-security-compliance-azure-pipeline), click the button <kbd>Launch Exercise</kbd>.
2. 404 Not Found is seen on page with link https://microsoftlearning.github.io/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/Instructions/Labs/AZ400_M07_L15_Implement_Security_and_Compliance_in_an_Azure_Pipeline.html
![image](https://user-images.githubusercontent.com/72177353/206615244-aa61e7f5-5295-4db4-ab78-580731e1db06.png)

### Correction being requested:

Change the link to:
https://microsoftlearning.github.io/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/Instructions/Labs/AZ400_M07_L16_Implement_Security_and_Compliance_in_an_Azure_Pipeline.html
(lab number had changed from L15 to L16)

### Lab

Lab 15 Implement security and compliance in Azure DevOps Pipelines

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
Thank you @k-byun! We are working on updating all lab pages with the new Lab links. It should be fixed soon.

**Comment by LuizMacedo** [comment]
I confirmed the issue is now resolved. Thank you!
