### ISSUE TITLE
M00-LAB00: Remove Task 20 (Demo Generator reference)

### ISSUE THREAD

**Issue by fimdim** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#339]
### What happened?

Exercise : 00
Task: 20

Description of issue: Demo Generator reference

### Lab

Lab 00 Validate lab environment

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
PR #340 merged, and the issue was fixed. Thanks!
