### ISSUE TITLE
M03-LAB08: Update Lab module name

### ISSUE THREAD

**Issue by fimdim** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#341]
### What happened?

Description of issue: Update Lab module name to "Create and manage containers using Docker and Kubernetes"

### Lab

Lab 08 Deploying Docker Containers to Azure App Service web apps

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
PR #342 was approved, and issue resolved. Thank you!
