### ISSUE TITLE
M05_L13

### ISSUE THREAD

**Issue by jajjaf** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#344]
### What happened?

Exercise : 1
Task: 2
Step: 4

When I run the build pipeline I get an error on the task "Push Docker Compose"
 ##[error]denied: requested access to the resource is denied
##[error]The process '/usr/bin/docker' failed with exit code 1

### Lab

Lab 13 Integrate Azure Key Vault with Azure DevOps

### Relevant screenshots

<img width="670" alt="error" src="https://user-images.githubusercontent.com/70439383/207559893-3fb0dc33-8523-480a-aaa0-ad2a94ad7d54.png">

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by chakra146** [comment]
+1

**Comment by chakra146** [comment]
@jajjaf  there is small typo on the parse bicep task in eshoponweb-ci-dockercompose.yml file.

in the line 53 it should be $value=$var.**acrloginServer**.value instead of $value=$var.loginServer.value.

after this the build and push are successful.

**Comment by LuizMacedo** [comment]
Closing the issue. Fixed in eShopOnWeb for AZ-400 repo.
