### ISSUE TITLE
M05_L14: Use the right pipeline file name for CD

### ISSUE THREAD

**Issue by fimdim** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#346]
### What happened?

Exercise : 01
Task: 02
Step: 07

Description of issue: CI pipeline file name used instead of CD

### Lab

Other

### Relevant screenshots

New Lab: App Config

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
PR #347 merged, and the issue was fixed. Thanks, @fimdim!
