### ISSUE TITLE
AZ400_M04_L09 | Alerts not getting triggered 

### ISSUE THREAD

**Issue by chakra146** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#348]
### What happened?

Exercise : 04
Task: 01
Step: 00

Description of issue:
The lab describes to create alerts for failed requests in Exercise 0, Task 3. However, the steps continue to deploy the webapp successfully and the app comes up. There are no failed requests observed. How would we get the failed alerts as described in exercise 4, task 1, step 2.

Repro steps:
1. Created release gates as per the instructions, but while testing the gates step 2 and 7 "For the Query Azure Monitor Alerts, notice an initial failed state." There are no failed alerts. when the pipeline is successfully deployed, how would we get the failed alerts.

### Lab

Lab 09 Control Deployments using Release Gates

### Relevant screenshots

![image](https://user-images.githubusercontent.com/61271207/209648256-0d769044-f839-4cfa-8cf8-0c16ae95a816.png)

![image](https://user-images.githubusercontent.com/61271207/209648288-dd0f07f1-d1ab-4356-a38a-284546d4d6e4.png)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
@petender @LuizMacedo I think this part may be missing from the last big update, how to trigger the fail request on the canary website: 
![image](https://user-images.githubusercontent.com/64772417/216326706-d95378f1-0d0a-48fc-88c0-bedcae86177c.png)

**Comment by petender** [comment]
Well yes, because the fault simulation isn't integrated in the EshopOnWeb app we use now instead, correct?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by unaihuete93** [comment]
of course! completely forgot that! maybe we could try calling some inexistent path or so

**Comment by unaihuete93** [comment]
@LuizMacedo @petender should we include it for next update? we need to trigger a failure

**Comment by LuizMacedo** [comment]
Yes, let's include to our list.

**Comment by LuizMacedo** [comment]
Lab refreshed, closing the issue.
