### ISSUE TITLE
LAB04: Visual Studio as a Prerequisite for Build Agent

### ISSUE THREAD

**Issue by shurick81** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#351]
### Contact Details

alexander@sapozhkov.net

### What happened?

Exercise : 02
Task: 01
Step: 26

Description of issue:
Instead of succesful pipeline run, I see `No agent found in pool az400m05l05a-pool which satisfies the following demand: visualstudio. All demands: agent.name -equals az400m05-vm0, msbuild, visualstudio, Agent.Version -gtVersion 2.182.1`

Repro steps:
1. Run the learning script on an empty lab VM

### Lab

Lab 04 Configuring agent pools and understanding pipeline styles

### Relevant screenshots

<img width="960" alt="image" src="https://user-images.githubusercontent.com/11289124/210186235-a6061941-73a6-4b04-939d-5f396d38454c.png">

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by gillianstravers** [comment]
Same here :(

**Comment by markvader** [comment]
Same, I have Visual Studio Code v1.74.3 installed but this is not recognised as satisfying the prerequisites for the agent

**Comment by unaihuete93** [comment]
@LuizMacedo the skillable lab VMs meet this demands, maybe we need to include prerequisites for those following the lab for other computing options.

**Comment by sbonds** [comment]
> maybe we need to include prerequisites for those following the lab for other computing options

That would be great, as many of us are doing this lab as part of a self-paced Microsoft Learn curriculum, not just in an instructor-led lab environment. A document about setting up an evaluation Windows Server host would be great. Or at least a quick description of what should be installed that's not part of a base OS install. A step to check the capabilities of the agent after setup might also be useful.

Visual Studio Build Tools was not enough. To get the `VisualStudio` capability to appear in the agent capabilities list, I installed Visual Studio Community 2022 and rebooted the server. Installation was not enough. A restart of the agent may have been enough, but a full reboot worked for me.

**Comment by LuizMacedo** [comment]
I loved your suggestion, @sbonds. We will study and implement it in our future updates. Thank you!
