### ISSUE TITLE
M06-LAB14: Cmdlet New-AzureStorageContainer incorrect

### ISSUE THREAD

**Issue by gillianstravers** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#357]
### What happened?

Exercise : 01
Task: 03
Step: 06+07

Description of issue:
task 6
New-AzureStorageContainer should be New-AzStorageContainer
task 7
Set-AzureStorageBlobContent should be Set-AzStorageBlobContent
New-AzureStorageBlobSASToken should be New-AzStorageBlobSASToken

### Lab

Lab 14 Azure deployments using Azure Resource Manager templates

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/issues/374

**Comment by LuizMacedo** [comment]
Fixed by #374. Thanks @gillianstravers!
