### ISSUE TITLE
M04-LAB10: No "Add a database" slider

### ISSUE THREAD

**Issue by Ezema** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#358]
### What happened?

Exercise : Module 4: "Creating a Release Dashboard"
Task: 01
Step: 04

Description of issue:
There's no "Add a database" slider when choosing ASP.NET Core
Repro steps:
Just following the LAB instructions, there's no "Add a database" slider or button anywhere to be found. Screenshot attached.

### Lab

Lab 10 Creating a release dashboard

### Relevant screenshots

![Screenshot from 2023-01-24 15-25-46](https://user-images.githubusercontent.com/20975719/214320376-afbf2135-2f79-4fe6-8ed0-43d3a4196268.png)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
@LuizMacedo @petender delete lab, Lab Starter will be retired in March

**Comment by LuizMacedo** [comment]
Closing this issue since the lab is now deprecated by #422. Thanks!
