### ISSUE TITLE
instructions are not clear

### ISSUE THREAD

**Issue by Usamawahabkhan** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#36]
# Module: 01
#### Step: 11

Description of issue

instructions is not clear   set the estimated number all of the time attendees look for this feature but its just out their. 
refer  it as square box or something.  

On the Taskboard tab of the Sprints view, in the rectangle representing the Add page for most recent tutorial, set the estimated number of hours to match your total capacity for this sprint, which you identified in the previous step.

Repro steps:

1.
1.
1.

**Comment by krasmuss** [comment]
As suggested, changed step 11 of Task 3 to read:

On the Taskboard tab of the Sprints view, in the square box representing the Add page for most recent tutorial, set the estimated number of hours to match your total capacity for this sprint, which you identified in the previous step.
