### ISSUE TITLE
M05-LAB11 and M07-LAB16 Fix eShopOnWeb repo links

### ISSUE THREAD

**Issue by fimdim** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#361]
### What happened?

Description of issue: Update links to point to the new eShopOnWeb repository.

### Lab

Other

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
closing as it was merged (for some reason linked issue did not work)
