### ISSUE TITLE
M04-LAB09: NEED TO CHANGE SIGNAL NAME 

### ISSUE THREAD

**Issue by sattract** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#366]
### Contact Details

skastwal701@gmail.com

### What happened?

Exercise : 00
Task: 04
Step: 14

Description of issue: It is saying to search Signal Name as Failed requests under **create a rule** for alerts but we cannot find any signal name with failed requests. It should be changed to **Requests** In place of **Failed Request**

Repro steps:
1. Change **Failed Requests** to **requests** under signal name when searching. Using Requests signal we can follow the lab further.

![image](https://user-images.githubusercontent.com/114693937/215894777-9fe99267-e860-499c-8227-4f0cee2a1f13.png)

### Lab

Lab 09 Control Deployments using Release Gates

### Relevant screenshots

![image](https://user-images.githubusercontent.com/114693937/215894792-cc151f1b-8b23-41a6-ba9b-950af4044844.png)

![image](https://user-images.githubusercontent.com/114693937/215895157-0a0071f7-ee9e-43fc-ac6a-1ba393bcf40d.png)

![image](https://user-images.githubusercontent.com/114693937/215895297-8db7a5c1-05f2-4938-b7f9-81495d611ee6.png)

### Do you want to help us? 👏

- [X] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
You need to make sure you are opening an alert **inside application insights**. The signal exists:
![image](https://user-images.githubusercontent.com/64772417/216042645-41d0ff2f-4f23-4ac2-b5da-755ded96a211.png)

@LuizMacedo closing it for now, maybe a warning could be included, as many people face this issue.
