### ISSUE TITLE
M04-L09_Controlling_Deployments_using_Release_Gates: Signal not clear

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#384]
### Contact Details

mkennten@microsoft.com

### What happened?

Exercise : 01
Task: 04
Step: 14

"On the Select a signal blade, in the Search by signal name textbox, type Requests and select it."

Step 14. tells me to search for Requests, but there are three different ones and I need to select Failed Requests. It used to say this, not sure why this was changed.

![image](https://user-images.githubusercontent.com/37703728/218767567-390ccdce-03a6-4210-a58c-3d1de84633f9.png)

### Lab

Lab 09 Control Deployments using Release Gates

### Relevant screenshots

see above

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by petender** [comment]
There is a difference in alerts signals, depending how you start the creation. As per the instructions, if you start from Application Insights, next select alerts, it will show the following search results for "requests"

![image](https://user-images.githubusercontent.com/62486122/226053855-78213e98-b847-45d6-bda7-13695cf4c06e.png)

However, if you directly go to Alerts (outside of App Insights...), it shows the following results:

![image](https://user-images.githubusercontent.com/62486122/226054297-f3f15398-cfba-4b89-8d51-becae57f8ed1.png)

The lab instructions are correct, just confusing why the alerts behavior is different, depending on how you start the configuration.

**Comment by mkennten** [comment]
You misread the point, but I see that the instructions have changed a lot since I reported this issue and no it is clarified which of the "requests" needs to be selected:

"On the Configure signal logic blade, search for and select the **Failed requests** metric."

It is not confusing to see different signals when the scope is different. Before it just didn't say which signal to select.
