### ISSUE TITLE
M03_L06_Integrating_External_Source_Control_with_Azure_Pipelines: "Create Fork" step missing

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#385]
### Contact Details

mkennten@microsoft.com

### What happened?

Exercise : 01
Task: 02
Step: 02

If you follow the steps closely you will NOT click the button Create Fork to actually create the fork in your repositories. Since all other instructions are super detailed, it should be added to click the button.

![image](https://user-images.githubusercontent.com/37703728/218791151-0363eb2d-e574-434b-8a86-ebf28e8c32cb.png)

### Lab

Lab 06 Integrating external source control with Azure Pipelines

### Relevant screenshots

see above

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
Closing this issue since the lab is now deprecated by #422. Thanks!
