### ISSUE TITLE
M00-LAB00: Update project to remove warnings

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#387]
### Contact Details

mkennten@microsoft.com

### What should we change?

Currently the eShopOnWeb projects throws 100+ warning during a build. Not a real issue but also not necessary, could this please be updated to avoid those warning or at least most of them.

### Lab

Other

### Relevant screenshots

![image](https://user-images.githubusercontent.com/37703728/219051923-c2e68a9f-ff3d-4440-afc3-ccebb6293419.png)

**Comment by LuizMacedo** [comment]
Closing the issue. We will update the https://github.com/MicrosoftLearning/eShopOnWeb to .NET 7, for now (.NET 8 coming) and that should resolve almost all warnings from what we saw.
