### ISSUE TITLE
M04-LAB08: docker CI should clarify RG to use 

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#388]
### What happened?

Lab mentions to use RG created before, but there is no RG created before. Learner should just replace NAME with desired value, the pipeline will create a RG for them. 
![image](https://user-images.githubusercontent.com/64772417/219058859-aea3d46a-40ac-4c7b-937c-f63dbb1d4552.png)

### Lab

Lab 08 Deploying Docker Containers to Azure App Service web apps

### Relevant screenshots

![image](https://user-images.githubusercontent.com/64772417/219058889-8069f16e-17e8-4286-b23f-2cbdc06c5e55.png)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by fimdim** [comment]
@unaihuete93 The resource group should be created in **Exercise 2 -> Task 1** (CI pipeline).
And if it's not the case, it's referred to as **defined before in the lab** and not **created before**.

**Comment by unaihuete93** [comment]
@fimdim bug is not applicable anymore, instructions were changed some time ago 
![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/64772417/2f739f54-9a60-434f-8ed6-ec8083681e0a)
Lets close it :)
