### ISSUE TITLE
M06_L15: Add step to create ResourceGroup az400m13l01-RG

### ISSUE THREAD

**Issue by Jbekker** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#396]
### What should we change?

At around line ~231 the resource group az400m13l01-RG is mentioned:
`az deployment group what-if --name az400m13l01deployment --resource-group az400m13l01-RG --template-file main.bicep` 

A step should be added to create that resource group at the start of Task 3 or at least or at least before it's being used to deploy the resources.

### Lab

Other

### Relevant screenshots

None

**Comment by petender** [comment]
https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/pull/399
