### ISSUE TITLE
M01-LAB01: The sprint length and descriptions do not match

### ISSUE THREAD

**Issue by yashints** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#400]
### What happened?

Exercise : 01
Task: 01
Step: 09

Description of issue: The length of the sprints are 3 weeks, however, not only the screenshot is misleading, but also the next description incorrectly mentions the current sprint is the second. Also, later when the sprint is set for work items it's sprint 2 which means students would not see them when they go to the current sprint. So, all consequent instructions should be verified to make sure dates are set correctly. 

Repro steps:
1. Follow the instructions up until task 1 step 9.
1. Set the dates according to the instructions.
1. Current sprint will be one not too.

### Lab

Lab 01 Agile planning and portfolio management with Azure Boards

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by fimdim** [comment]
Thanks @yashints ! @petender is working on that.

**Comment by petender** [comment]
Lab guide has been updated to reflect a correct 3-week Sprint timeline, as well as more clear instructions + updated screenshot. Updates done. Closing issue after PR got merged

**Comment by LuizMacedo** [comment]
Issue resolved. Thank you all!
