### ISSUE TITLE
M05-LAB09: Unavailable essential link

### ISSUE THREAD

**Issue by ahtkun** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#409]
### Contact Details

ahmedtamer1078@gmail.com

### What should we change?

The [Deploy to Azure] link in M05-L09 is unavailable

### Lab

Lab 12 Setting up and running functional tests

### Relevant screenshots

![Capture](https://user-images.githubusercontent.com/105516084/227250067-33cb5c5a-50ef-487a-b8aa-94453e385818.PNG)

**Comment by LuizMacedo** [comment]
Link is working fine for me. Can you double check @petender @fimdim? Thanks!

**Comment by fimdim** [comment]
> Link is working fine for me. Can you double check @petender @fimdim? Thanks!

@LuizMacedo I confirm that the link is working.

**Comment by LuizMacedo** [comment]
Thanks @fimdim.
Closing the issue for now. Feel free to reopen if you see the link broken. Thanks @ahtkun.
