### ISSUE TITLE
M04-LAB10: Impossible to create the DevOps starter

### ISSUE THREAD

**Issue by rmajid2** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#410]
### Contact Details

r.majid2@gmail.com

### What happened?

Exercise : 01
Task: 01
Step: 02

Description of issue:
Error when trying to create the DevOps starter
![image](https://user-images.githubusercontent.com/36069828/229829952-9096629f-b8dd-4b2a-ac03-58b8f386f247.png)

DevOps Starter is [retired since March 31, 2023](https://learn.microsoft.com/en-us/previous-versions/azure/devops-project/overview).

![image](https://user-images.githubusercontent.com/36069828/229830820-fa81b8c6-e1cd-4beb-a37f-75f26b3b7ee5.png)

Repro steps:
1.navigate to the [Azure Portal](https://portal.azure.com/)
2.In the Azure portal, search for and select the DevOps Starter resource type and, on the DevOps Starter blade, click + Create.

### Lab

Lab 10 Creating a release dashboard

### Relevant screenshots

![image](https://user-images.githubusercontent.com/36069828/229830099-0411ae47-00c9-4dbc-afb4-65391a3a34ae.png)

![image](https://user-images.githubusercontent.com/36069828/229830844-ec9ba5dc-28ea-420c-9c77-690f63f29872.png)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
Closing this issue since the lab is now deprecated by #422. Thanks!
