### ISSUE TITLE
M00-LAB13 keyvault

### ISSUE THREAD

**Issue by true-while** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#413]
### Contact Details

aivanov@Microsoft.com

### What happened?

Exercise : 01
Task: 02
Step: 03

Description of issue:

Task 2 Step 3 the instructions want you to provide '/.ado/eshoponweb-ci-dockercompose.yml' but the file is named '/.ado/**eshoponweb-cd-aci.yml**' it autocompletes correctly. 

### Lab

Lab 13 Integrate Azure Key Vault with Azure DevOps

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by fimdim** [comment]
@true-while **/.ado/eshoponweb-ci-dockercompose.yml** is used as the CI pipeline.
**/.ado/eshoponweb-cd-aci.yml** is used as the CD pipeline.
