### ISSUE TITLE
M00-LAB: Managing technical debt with SonarCloud and Azure DevOps

### ISSUE THREAD

**Issue by true-while** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#414]
### Contact Details

aivanov@Microsoft.com

### What happened?

Exercise : 01
Task: 01
Step: 01

Description of issue:
Option to select public/private project are not visible because that default settings of organization is not allowed public project. Learners need to go in organization settings to allow public projects.

### Lab

Lab 16 Managing technical debt with SonarQube and Azure DevOps

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by fimdim** [comment]
This is now part of [Validate lab environment](https://microsoftlearning.github.io/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/Instructions/Labs/AZ400_M00_Validate_lab_environment.html).
Thanks @true-while.
