### ISSUE TITLE
M01-LAB01: Agile Planning and Portfolio Management with Azure Boards

### ISSUE THREAD

**Issue by gchoquetMS** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#416]
### Contact Details

gchoquet@microsoft.com

### What happened?

Exercise : 01
Task: 01
Step: 10

Description of issue:
screenshot of sprint durations are overlapping which brought confusion with learners. 
Recommend to update to 
sprint 1 : 4/3 to 4/21 

sprint 2 : 4/24 to 5/ 12

sprint 3 : 5/15 to 6/2

### Lab

Lab 01 Agile planning and portfolio management with Azure Boards

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by petender** [comment]
Hey, this issue has been reported before, and there is a pending PR (https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/pull/404) with the fixed explanation and screenshots already available. Waiting for the content team to approve the updates and close the issue.

**Comment by petender** [comment]
Hmm, looks like there are 2 at the start of the lab that got left behind for updates...

Will move them into the PR so having this fixed asap

***@***.***
Peter De Tender
Microsoft Technical Trainer
M:425 691 6411
***@***.******@***.***>      | @pdtit<https://twitter.com/pdtit>     | https://aka.ms/pdtit
Learn.Microsoft.com<https://learn.microsoft.com/>
Microsoft Learn. Spark possibility.

**Comment by LuizMacedo** [comment]
It's fixed by #404. Closing the issue. Thanks @gchoquetMS and @petender!
