### ISSUE TITLE
M03-LAB01: Configuring Agent Pools and Understanding Pipeline Styles

### ISSUE THREAD

**Issue by gchoquetMS** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#417]
### Contact Details

gchoquet@microsoft.com

### What happened?

Exercise : 01
Task: 01
Step: 04 and 5

Description of issue:
step is missing to configure pipeline. Participants got confused if they had to use ASP.NET. ASP.NET Core, .NET Desktop .... 

Adding 1 line on the sequence of actions would remove the confusion. (see screenshot)

### Lab

Lab 04 Configuring agent pools and understanding pipeline styles

### Relevant screenshots

paste here 😉
![image](https://user-images.githubusercontent.com/73969245/231240887-bb9b28f4-0a37-4957-b911-665bb82aa28b.png)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by petender** [comment]
In this lab, learners are supposed to using the YAML pipelines, not the classic version.

As per the instructions:

Exercise 1: Author YAML-based Azure Pipelines

In this exercise, you will convert a classic Azure Pipeline into a YAML-based one.

Task 1: Create an Azure DevOps YAML pipeline

In this task, you will create a template-based Azure DevOps YAML pipeline.

  1.  From the web browser displaying the Azure DevOps portal with the Configuring Agent Pools and Understanding Pipeline Styles project open, in the vertical navigational pane on the left side, click Pipelines.
  2.  On the Recent tab of the Pipelines pane, click New pipeline.
  3.  On the Where is your code? pane, click Azure Repos Git.
  4.  On the Select a repository pane, click PartsUnlimited.
  5.  On the Review your pipeline YAML pane, review the sample pipeline, click the down-facing caret symbol next to the Run button, click Save.

The YAML pipeline will detect the correct ASP.NET dependencies to use for the different tasks in the pipeline.

Thx, Peter





From: gchoquetMS ***@***.***>
Sent: Tuesday, April 11, 2023 10:26 AM
To: MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions] M03-LAB01: Configuring Agent Pools and Understanding Pipeline Styles (Issue #417)

Contact Details

***@***.******@***.***>

What happened?

Exercise : 01
Task: 01
Step: 04 and 5

Description of issue:
step is missing to configure pipeline. Participants got confused if they had to use ASP.NET. ASP.NET Core, .NET Desktop ....

Adding 1 line on the sequence of actions would remove the confusion. (see screenshot)

Lab

Lab 04 Configuring agent pools and understanding pipeline styles

Relevant screenshots

paste here 😉
[image]<https://user-images.githubusercontent.com/73969245/231240887-bb9b28f4-0a37-4957-b911-665bb82aa28b.png>

Do you want to help us? 👏

  *   [ ] Create a Pull Request by following this project's Contribution Guide<https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate>

**Comment by LuizMacedo** [comment]
Closing the issue. See @petender suggestion for details.
