### ISSUE TITLE
AZ400_M04_L10_Creating_a_Release_Dashboard.md

### ISSUE THREAD

**Issue by aparnakhadatkar** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#419]
### Contact Details

aparna.khadatkar@spektrasystems.com

### What happened?

Exercise : 01
Task: 01
Step: 02

Description of issue: DevOps Starter is not available through the search box in azure. It is available through the marketplace. As the DevOps Starter is now retired On 31 March 2023, should we update this lab?

Repro steps:
1. On your lab computer, start a web browser, navigate to the [Azure Portal](https://portal.azure.com/) and sign in with the user account that has the Owner or Contributor role in the Azure subscription you will be using in this lab.

2. n the Azure portal, search for and select the DevOps Starter resource type and, on the DevOps Starter blade, click + Create.

### Lab

Other

### Relevant screenshots

![image](https://user-images.githubusercontent.com/99411739/231700084-795d7f86-c068-4085-89e8-7168b1f86bdd.png)

<img width="645" alt="image" src="https://user-images.githubusercontent.com/99411739/231700304-72418f27-d686-4472-beae-9b5d55a9c4b2.png">

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
Closing this PR since the lab is now deprecated by #422. Thanks!
