### ISSUE TITLE
AZ400_M00_Validate_lab_environment: "Work item process" needs to be set to "Scrum"

### ISSUE THREAD

**Issue by microsmith** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#423]
### Contact Details

mike@maxtrain.com

### What happened?

Exercise : 0
Task: 1
Step: 1

Description of issue:

  Instructions only say to name the project and click Create. This creates a project with a "Work item process" set to "Basic". 

  Note the screen capture shows "Advanced" as expanded and  "Work item process" set to "Scrum".

  The "Basic" setting breaks "AZ400_M02_L02_Version_Controlling_with_Git_in_Azure_Repos", Exercise 4, Task 6, Step 2 "Click on + New Work Item > Product Backlog Item." as there is no "Product Backlog Item" option.

### Lab

Lab 00 Validate lab environment

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by microsmith** [comment]
Note that you could just delete "Instructions to create the sample Azure DevOps Project (you only have to do this once)" in Module 0 as it is repeated (with the additional correct step to select "Scrum") in Module 1 ("Agile Planning and Portfolio Management with Azure Boards").

**Comment by LuizMacedo** [comment]
Fixed by #424. Thanks @microsmith!
