### ISSUE TITLE
Lab 08: Deploying Docker containers to Azure App - 

### ISSUE THREAD

**Issue by microsmith** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#430]
### Contact Details

mike@maxtrain.com

### What happened?

Exercise : 02
Task: 01
Step: 08   (It's labeled step 1 in the current version of the lab. Previous step is 7.)
     "1. Click on Save and Run and wait for the pipeline to execute successfully"

Description of issue:

Clicking "Save and Run" in the "Save and run" dialog box displays:
  `TF402455: Pushes to this branch are not permitted; you must use a pull request to update this branch.`

I believe this is due to a change in an earlier lab to the eShopOnWeb project.
**Disabling "Require a minimum number of reviewers" lets the lab continue.**

We either need to reset this change, or ask the students to create a new project.

Repro steps:
1.
1.
1.

### Lab

Other

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
Thanks @microsmith. We will have this fixed in our next release. You should see the PR soon.
