### ISSUE TITLE
AZ400_M01_L01_Agile_Planning... missing step

### ISSUE THREAD

**Issue by microsmith** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#431]
### What happened?

Exercise : 01
Task: 01
Step: 06

Description of issue:

Student is not instructed to click the "EShop-Web" link to open the page that has the "Iterations and Areas Paths" link.

### Lab

Lab 01 Agile planning and portfolio management with Azure Boards

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
Thanks @microsmith.

Step 5 resolves the issue. 

<img width="661" alt="image" src="https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/45747223/480c128d-e588-4ab3-a07a-728b11a1db16">
