### ISSUE TITLE
AZ400: Architecture Diagrams not available

### ISSUE THREAD

**Issue by akn9050** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#432]
### Contact Details

akn9050@gmail.com

### What should we change?

PROPOSAL:

In other Labs, like Az-104, Az-204, I have seen the architecture diagrams for each lab defined with Tasks, but it is not available for AZ-400. Are you planning to add these diagrams? This helps to get a high-level idea about the lab after seeing the architectural Diagram.  Please see Az-104 as an example: https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/blob/master/Instructions/Labs/LAB_02a_Manage_Subscriptions_and_RBAC.md#architecture-diagram

**Comment by LuizMacedo** [comment]
Great feedback, @akn9050! We can add more diagrams to our labs and content. I'll add it to our list and discuss it for our following updates. We should have more changes coming after August when we will rediscuss our plans for AZ-400 next year.

Thank you!

cc @petender @fimdim

**Comment by fimdim** [comment]
Totally agree. This would be a great improvement.
Thanks @akn9050 !

**Comment by LuizMacedo** [comment]
Closing the issue. It's added to our plans.
