### ISSUE TITLE
M08_L15: Indentation errors to be fixed

### ISSUE THREAD

**Issue by alexcalabrese** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#437]
### Contact Details

alexcalabrese0802@gmail.com

### What happened?

The are some spaces that made the file not well formatted.

### Lab

Lab 15 Package management with Azure Artifacts

### Relevant screenshots

![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/58480609/cc80f7bb-b666-4fd2-83f3-cfe473c0eb0c)

![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/58480609/b86bac66-fdf3-4a83-9289-8af3baabb6bb)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
Fixed by #434. Thanks!
