### ISSUE TITLE
M03-LAB01: Self-Agent install PS script should be on separate lines

### ISSUE THREAD

**Issue by petender** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#442]
### Contact Details

petender@microsoft.com

### What happened?

Exercise : 02
Task: 01
Step: 13

The code snippet shows the following:

cd \
mkdir agent ; cd agent
$TARGET = Get-ChildItem "$Home\Downloads\vsts-agent-win-x64-*.zip"
Add-Type -AssemblyName System.IO.Compression.FileSystem
[System.IO.Compression.ZipFile]::ExtractToDirectory($TARGET, "$PWD")

which gives the impression it should all be part of the same line. Consider emphasizing it's actually 2 split commands:

First run: 
$TARGET = Get-ChildItem "$Home\Downloads\vsts-agent-win-x64-*.zip"

followed by running: 
Add-Type -AssemblyName System.IO.Compression.FileSystem
[System.IO.Compression.ZipFile]::ExtractToDirectory($TARGET, "$PWD")

Repro steps:
1. If you copy everything on the same line, the PowerSHell script throws an error" Get-ChildItem: A Parameter cannot be found that matches parameter name 'AssemblyName' 
1.
1.

### Lab

Lab 03 Configuring agent pools and understanding pipeline styles

### Relevant screenshots

![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/62486122/4fae915c-5489-4d2d-b4a1-7454586bcb59)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by mkems** [comment]
It doesn't give me the impression to use this on one line at all, hence its separate lines. And it works fine if you just copy & paste.

**Comment by petender** [comment]
yes, got fixed with a 'new line return' in the description...

**Comment by fimdim** [comment]
@LuizMacedo This should be marked as closed as it was already implemented by @petender.

**Comment by LuizMacedo** [comment]
Thanks all!
