### ISSUE TITLE
M04-LAB "Controlling Deployments using Classic Release Gates": Pipeline to pick not stated

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#446]
### What happened?

Exercise : 02
Task: 03
Step: 07

Description of issue:
Name of the pipeline to pick should be mentioned in the instruction because it's not just "eShopOnWeb" but should be "eshoponweb-ci" - and if that project was re-used, you might even see more than this one in the pulldown list.

### Lab

Lab 07 Control Deployments using Release Gates

### Relevant screenshots

<img width="713" alt="image" src="https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/37703728/e6a854ba-02d7-458b-887b-85d895143815">

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by fimdim** [comment]
Thanks @mkennten ! PR was created.
