### ISSUE TITLE
M08-Package Management with Azure Artifacts: Creation of Nuget package fails

### ISSUE THREAD

**Issue by mkems** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#449]
### What happened?

Exercise : 01
Task: 02
Step: 16

Description of issue:
When running the command to create the nupkg file an error message states that "SDK-style projects is not supported" (see screenshot for details). nuget.exe version is 6.6.1.2.

### Lab

Lab 15 Package management with Azure Artifacts

### Relevant screenshots

<img width="851" alt="image" src="https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/76537894/a929a2a0-33ed-42d7-af84-c0845f40e55b">

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
Issue was fixed by #462.
