### ISSUE TITLE
M03-L06 "Deploying Docker containers to Azure App Service web apps": Instructions are not matching when this is the first lab

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#453]
### What happened?

Exercise : 02
Task: 01
Step: 02

Description of issue:
Labs do not depend on others, and it should be possible to run them in any order. If you do run this lab as a first and have not yet imported any pipeline, then the following instruction is not matching the UI:

Click on New pipeline button

If it's the first one, then there's only a "Create Pipeline" button, see screenshot.

Step 3:
Select Azure Repos Git (Yaml)
should be
Select Azure Repos Git (YAML)

Step 5:
Select Existing Azure Pipelines YAML File
should be
Select Existing Azure Pipelines YAML file

In addition, once any new pipeline is started (for the first time) it's waiting for approval to allow using the service connection (which haven't been used before). This needs to be mentioned. See screenshot.

### Lab

Lab 06 Deploying Docker Containers to Azure App Service web apps

### Relevant screenshots

<img width="538" alt="image" src="https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/37703728/24e9846b-7a52-4326-b6a8-8c685212859c">

![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/37703728/57d10b1e-ae7a-4a7a-96bf-3607a2823385)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by mkems** [comment]
Creates pull request #466 today with fixes one of these issues - once the PR got approved and is merged I will fix the remaining issues from this as well.

**Comment by LuizMacedo** [comment]
#469 resolved the issue. Thank you so much @mkems!
