### ISSUE TITLE
M05-LAB08: Configuring Pipelines as Code with YAML: Instructions to add approvals/checks to environment need updating

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#455]
### What happened?

Exercise : 02
Task: 01
Step: 07-10

Description of issue:
UI has changed and the instructions for adding the Approval/Checks need to be updated, see screenshots.

### Lab

Lab 08 Configuring pipelines as code with YAML

### Relevant screenshots

<img width="302" alt="image" src="https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/37703728/d8714cf4-2137-4a72-b3b9-68f17706813f">

<img width="366" alt="image" src="https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/37703728/50b2f249-55a1-4727-85b3-7425e0cb0150">

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
Issue closed. Image is removed.
