### ISSUE TITLE
Lab 20 missing steps at Exercise 1 > Task 2 > Step 6

### ISSUE THREAD

**Issue by easynut** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#46]
![image](https://user-images.githubusercontent.com/19815045/108296622-dd048b00-71d4-11eb-8f77-6933ed8d41a2.png)

Missing steps, prior to Step 6, it should mention that learners must go to Azure Pipeline > Pipelines > Create a new pipeline

**Comment by krasmuss** [comment]
Step 6 was updated for clarification as follows:

Switch back to the web browser tab displaying the **Where is your code?** pane.  If you have closed this tab, return to the **SonarExamples** pane in the Azure DevOps portal, in the vertical menu bar at the far left of the Azure DevOps portal, click **Pipelines** and then click **Create Pipeline**.
