### ISSUE TITLE
M03-LAB04: Replace .Net 6 reference with .Net only

### ISSUE THREAD

**Issue by fimdim** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#472]
### What should we change?

Replace .Net 6 reference by .Net only

### Lab

Lab 04 Enabling continuous integration with Azure Pipelines

**Comment by fimdim** [comment]
@LuizMacedo This should be marked as closed as it was already implemented.

**Comment by LuizMacedo** [comment]
Resolved by #473. Thanks!
