### ISSUE TITLE
Remove the agent created during the exercise.

### ISSUE THREAD

**Issue by felipementel** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#479]
### Contact Details

felipementel@hotmail.com

### What should we change?

I'm studying for the AZ-400 and during my studies I was directed to do the lab below.

https://microsoftlearning.github.io/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/Instructions/Labs/AZ400_M03_L03_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.html

After completing the exercise, I saw that there was no guidance in the documentation on how to disassemble the environment, in this case, remove the Azure DevOps agent that was running as a service on my machine.

Analyzing the folder that was created, I found a file to do the complete removal
````
./config remove
````
I'm sure that teaching how to disassemble the environment created on the machine is very important, so I think it makes sense to be present in the exercise documentation.

### Lab

Lab 03 Configuring agent pools and understanding pipeline styles

### Relevant screenshots

![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/14238257/e4aa1eff-45f7-401d-9241-71ab0beeed76)

**Comment by fimdim** [comment]
@petender I think this is something we can add. What do you think?
