### ISSUE TITLE
M06-Deployments using Azure Bicep templates: simple-windows-vm.bicep file and .ado/eshoponweb-cd-windows-cm.yml NOT AVAILABLE

### ISSUE THREAD

**Issue by suketunayak** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#486]
### Contact Details

suketunayak@hotmail.com

### What happened?

Exercise : 01
Task: 01
Step: 01

Description of issue: In the browser tab you have your Azure DevOps project open, navigate to Repos and Files. Open the .azure\bicep folder and find the simple-windows-vm.bicep file.

simple-windows-vm.bicep **FILE NOT AVAILABLE**

![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/12823966/64f94373-2700-4ed5-b7e3-51c682cfae0f)

---------------------------------------------------------------------------------------------------
Exercise : 01
Task: 04
Step: 06

Description of issue: In the Selecting an existing YAML File blade, specify the following parameters:
Branch: main
Path: .ado/eshoponweb-cd-windows-cm.yml

Path: .ado/eshoponweb-cd-windows-cm.yml  **FILE NOT AVAILABLE**

![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/12823966/be170cd5-3f55-4140-8bb8-a095d4fdf134)

### Lab

Deployments using Azure Bicep templates

### Relevant screenshots

![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/12823966/e8fd005d-8c25-40c6-92ba-ae2ae34ccaaa)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by suketunayak** [comment]
Hello,

Now I am able to see this files.

![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/12823966/c4796171-0a13-4e8e-9e80-a2ce452ea4ec)


![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/12823966/74afa3e5-5b01-455e-a287-9788737047c7)



Thanking You

**Comment by fimdim** [comment]
@LuizMacedo This should be closed as it's not the case anymore after the last eShopOnWeb update.

**Comment by LuizMacedo** [comment]
Closing the issue since it's resolved in our last update. Thanks!
