### ISSUE TITLE
M05_L09: Missing course file prevents establishing connection to virtual machine

### ISSUE THREAD

**Issue by PavolUniqa** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#487]
### What happened?

ID	33175508
Host	EU-HV10
Datacenter	EU North (London)

Exercise : 00
Task: 00
Step: 00

Description of issue: Missing course file prevents establishing connection to virtual machine
Browser Console displays error:
Unable to successfully reach https://raw.githubusercontent.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/master/Instructions/Labs/AZ400_M05_L09_Setting_Up_and_Running_Functional_Tests.md. Response status code: NotFound.

I have switched off proxy in windows settings.
I have sign off from account in browser and used incognito mode.
Signing off and on from MS Account didn't help (on all sites).

Repro steps: Connection to virtual machine is not available straight from beginning.

### Lab

Other

### Relevant screenshots

![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/142328760/cb4c2a3e-915b-479f-80cc-093885d215a5)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by fimdim** [comment]
@PavolUniqa Thanks for the feedback. This issue is related to the LODS platform and not to this repo.
@LuizMacedo This should be marked as closed as it's not a GH issue.
