### ISSUE TITLE
Lab: Package Management with Azure Artifacts, Lab VM Failing

### ISSUE THREAD

**Issue by angyay0** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#49]
# Module: 09
#### Step: 08

Description of issue: When you open the VM and download the project trying to use with VS2019  Community it constantly gets an import issue with the package, pre-installed software is not installed in some VMs.

Repro steps:
1-  Clone PUL repo
2- Open  With VS2019

**Comment by krasmuss** [comment]
VS2017 has been added to the image.
