### ISSUE TITLE
AZ400_M08_L15_Package_Management_with_Azure_Artifacts.md - multiple issues

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#496]
### What happened?

Exercise : 00
Task: multiple
Step: multiple

Description of issue:

Lab does not work as-written.  Visual Studio 2022 not installed in VM from DLC, and repeated errors.

-The 'Requirements' section of this lab indicates the Student should install Visual Studio 2022.  This app is missing from the VM stock from the Download Center which has 2 older copies of Visual Studio installed, 2017 & 2019 installed - but not VS 2022.  **Is there a reason this new version of VS is not installed within the VM so as to prevent the time/install questions a Student might have to do every time they run this Course?**

-The install section of this lab states this:  *"...Visual Studio 2022 Community Edition available from Visual Studio Downloads page. Visual Studio 2022 installation should include ASP.NET and web development, Azure development, and .NET Core cross-platform development workloads..."*.  When I look at the install menu, I do see 'ASP.NET and web development' & 'Azure Development', I do not see an entry called 'NET Core cross-platform development'.  Googling *seems* to indicate this may now be builtin to VS 2022, but I do not know this for a fact - **if it does exist under a different name can you confirm what that name might be - or, alternatively, confirm that we do not need to install that 'workflow' in the Instructions?**

-On the assumption the above item is not required, (which may be wrong, am hoping people can clarify here) I proceeded with the VS 2022 install, and then ran this lab several times from scratch (setting up and using my DevOps Org, and experienced further issues:

-When clicking the 'Clone In Visual Studio' button, (In Exercise 0, Task 1, Step 4) I see this dialog box which (because this VM has had both VS 2017 & VS 2019 installed in the past) it pops 3 options for 'VS Web Protocol Handler'.  In theory, a Student might recognize the icon (3rd from the top) as the correct one for the newly-installed VS 2022, but it is confusing - and if one chooses wrong (and leaves the 'always use this app' checkbox checked by default, it will open the wrong version of VS:

<img width="214" alt="choose" src="https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/49700217/ba56e7a1-2f79-4682-9ed8-0f2da6b009f3">

-OK, I select the VS2022 Web Protocol Handler, and VS2022 does open - but as far as I can tell (and I have left it sitting for long periods of time, in case it was doing something in the background) whatever was supposed to happen automatically does not - VS2022 just sits there, not opening anything.  This occurs whether I 'Sign in' as my account, or not:

<img width="799" alt="noclone" src="https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/49700217/877c382b-612d-4732-b1b3-650ae0b7e734">

-Note that if I select the 2nd Web Handler in the list (for VS2019) it does work, after I have signed in to VS 2019, however this does not help us because we need VS2022 for this exercise for .NET 6.0:

<img width="801" alt="VS2017" src="https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/49700217/8266889d-2f1b-45b0-a8eb-067b606265c7">

-OK, so I Try manually cloning:

<img width="312" alt="manualclone" src="https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/49700217/43a71a4a-59cd-47cc-88e5-839ac47d5f27">

-Fails with error, then retried and it *seemed* like it was successful:

<img width="645" alt="cloneerror" src="https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/49700217/d5cf76ca-b12e-4623-a0a8-ca53a269ef47">

-Step 11 The available NuGet Distribution Versions has changed, recommended is now apparently v6.7.0:

<img width="369" alt="nuget" src="https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/49700217/c8e23479-e0e4-4807-a3e8-86716ab168ae">

-Step 11 & 16: At least in my instance, forced to clone manually, default path was C:\Users\Students\Source\Repos\EShopOnWeb.Shared not what is seen in Instructions.

-I tried nuget 6.7.0.127, but got error in Step 16:

<img width="428" alt="step16error" src="https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/49700217/899a5ca0-1f42-471f-aff9-77278b531e87">

-That error led me to recent issue https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/issues/449 which is closed as resolved, however it appears the fix was changing instructs in a different lab, not this one.

-I tried switching to the cmd I see in the error message ('dotnet pack ./EShopPnWev.Shared.csproj') which seems to have worked, except for a warning about a  missing readme, however now the command in Step 17 fails:

<img width="423" alt="step17error" src="https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/49700217/ba772c88-6f7a-4910-a612-1730924cfb6d">

- I then also tried the previous nuget version of 6.6.1.2, which did seem to work using the cmd in Step 16, but got the identical 404 error in Step 17.

-I've started several fresh instances and done a lot of testing but am blocked from completing this lab: Perhaps others here have some savvy advice to assist, either confirming I am making mistakes - or confirming any other behaviors and/or workaround that might help a Student proceed to successfully accomplish this lab.

### Lab

Other

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by petender** [comment]
Dear,

The lab is using the EShopOnWeb sample web application, which is based on .NET6.0. This version of .NET is not supported in Visual Studio 2019 (see this thread for more details from the Product Team - https://github.com/dotnet/core/issues/5567#issuecomment-1105996161). 

IT explains several failing steps in your testing, because of "not supported". Changing from Visual Studio 2019 GUI to command line doesn't help unfortunately. 

The lab got updated, based on the latest version of Visual Studio 2022, available at the time of writing the updates. It is also listed as a prerequisite version to go through this lab successfully.

If you have access to Azure, you could run an installation of the "Visual Studio 2022" Azure Marketplace image. 
For a local installation of Visual Studio 2022, the required components as listed in the instructions (ASP.NET and web development, Azure development) look like this in the installation manager:

![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/62486122/91665a75-bc3f-46fb-94d7-37a0908b8b7c)

.NET Core components is what you get from installing Visual Studio 2022, so normally no further actions needed to get those.

Closing this issue because of 'unsupported Visual Studio 2019 Version'

Thanks, Peter
