### ISSUE TITLE
Issue with Lab: Setting Up and Running Functional Tests Student lab manual while creating template

### ISSUE THREAD

**Issue by abhy201** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#50]
#Module 11: Implementing Continuous Deployment using Azure Pipelines
#### Step: 1 to 4

Description of issue
Issue with Lab: Setting Up and Running Functional Tests Student lab manual while creating template.

In exercise 0, Task2:Create Azure resources, Step 4. Review + Create with the given details throwing error. The custom deployment is failing and unable to process further with the rest of the lab.  

Below is the error message:
{"code":"InvalidContentLink","message":"Unable to download deployment content from 'https://gallery.azure.com/artifact/20161101/Microsoft.CustomScriptExtension-arm.2.0.50/Artifacts/MainTemplate.json'. The tracking Id is '2927f399-cd2e-476c-b4ac-992ff7f5be7d'. Please see https://aka.ms/arm-deploy for usage details."}

Repro steps:

1. Logged into lab.
2. After creating project, move to Step1 of Task2 in Exercise0. When we click the deploy to Azure button, it opens a custom deploy template in a new window outside the lab machine. 
3. After filling the required details, when we click review+finish> Validation Fails with errors. 
4. ERROR TYPE
Unable to download deployment content from 'https://gallery.azure.com/artifact/20161101/Microsoft.CustomScriptExtension-arm.2.0.50/Artifacts/MainTemplate.json'. The tracking Id is '2927f399-cd2e-476c-b4ac-992ff7f5be7d'. Please see https://aka.ms/arm-deploy for usage details. (Code: InvalidContentLink)

**Comment by ianclark500** [comment]
see https://github.com/microsoft/azuredevopslabs/issues/518

**Comment by TesterTesterson1004** [comment]
I just ran a test of this lab, and the link to issue referenced by ianclark500 appears to have borne fruit:  The template deploy was successful!  (looks like they updated w/fix ~15 days ago)   ...assuming others test this out and concur, I think this issue here can be closed.

**Comment by krasmuss** [comment]
Resolved
