### ISSUE TITLE
M01-LAB1: Need few updates, due to UI changes 

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#503]
### What happened?

Exercise : 00
Task: 
Step: 00

Description of issue:

- Now the user is not shown directly in the capacity tab, need to click on "Add user" explicitly 
![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/64772417/1f07a411-1cf4-49e2-934c-720a4a940541)

- It should be board settings on this one 
![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/64772417/5272f5be-1113-47e5-b1f9-2a755553a010)
![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/64772417/7cf03a57-b867-4afb-87ea-f1ec5ea403e5)

- Also settings for the Sprint Taskboard suffered some updates (see ADO and screenshot in instructions) 
![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/64772417/261619c6-09a8-41d9-acd1-9ee995a58382)

Repro steps:
1.
1.
1.

### Lab

Agile planning and portfolio management with Azure Boards

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by petender** [comment]
Full lab has been reviewed and updated both in content, wording, new screenshots and integrated other bug fixes
