### ISSUE TITLE
M05-L11 Fix eShopOnWeb repo unit test

### ISSUE THREAD

**Issue by rmajid2** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#504]
### Contact Details

No response

### What happened?

Exercise : 01
Task: 01
Step: 07

Description of issue:

Pipeline run fail as unit test ci task fire exeption 

>  Failed Microsoft.eShopWeb.UnitTests.MediatorHandlers.OrdersTests.GetOrderDetails.NotBeNullIfOrderExists [80 ms]
  Error Message:
   Assert.NotNull() Failure
  Stack Trace:
     at Microsoft.eShopWeb.UnitTests.MediatorHandlers.OrdersTests.GetOrderDetails.NotBeNullIfOrderExists() in /home/vsts/work/1/s/tests/UnitTests/MediatorHandlers/OrdersTests/GetOrderDetails.cs:line 38
--- End of stack trace from previous location ---
  Failed Microsoft.eShopWeb.UnitTests.ApplicationCore.Services.BasketServiceTests.AddItemToBasket.InvokesBasketRepositoryUpdateAsyncOnce [239 ms]
  Error Message:
   Moq.MockException : 
Expected invocation on the mock once, but was 0 times: x => x.UpdateAsync(Basket, CancellationToken)

![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/36069828/89d5b57c-4b26-4277-a37e-89a824b52db4)

Quickly verifying the source code of imported project, I find that [the mock of unit test is for "GetBySpecAsync"](https://github.com/MicrosoftLearning/eShopOnWeb/blob/9f7f3cf9897494a3732878de55e46db655678394/tests/UnitTests/MediatorHandlers/OrdersTests/GetOrderDetails.cs#L25C1-L26C34) 

![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/36069828/92fff634-3879-451f-a860-f06fba0be43b)

but a [recent commit](https://github.com/MicrosoftLearning/eShopOnWeb/commit/d88293a174a12d7ff87cf035aa64bc85acc7301b#diff-69e7b184e00cd4218a9bd4af987749bb6cf6346907956ad9380e9366cd3364d3) to the project changed the tested method to use "FirstOrDefaultAsync"

![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/36069828/bcd4b18f-eba9-4f1b-bffe-d5344fbd6e8c)

Repro steps:
Run the created pipeline

### Lab

Enable Dynamic Configuration and Feature Flags

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
Thanks @rmajid2, PR https://github.com/MicrosoftLearning/eShopOnWeb/pull/82 will be fixing the issue in eShopOnWeb repo.
