### ISSUE TITLE
.NET 7 is not installed on the Lab VM: Restoring packages fails...

### ISSUE THREAD

**Issue by tinodo** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#511]
### Contact Details

tinodo@microsoft.com

### What happened?

The lab "Configuring Agent Pools and Understanding Pipeline Styles" will fail because eShopOnWeb is now on .NET 7, which is not installed on the Lab VM:

`Time Elapsed 00:00:02.49
##[error]Error: The process 'C:\Program Files\dotnet\dotnet.exe' failed with exit code 1
##[error]Packages failed to restore
Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
Finishing: Restore`

You can resolve the issue by installing the latest .NET 7 Windows SDK from [Download .NET 7.0 (Linux, macOS, and Windows) (microsoft.com)](https://dotnet.microsoft.com/en-us/download/dotnet/7.0) and install it on the Lab VM.

### Lab

Configuring agent pools and understanding pipeline styles

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
Thank you @tinodo! I'll update the VM as soon as possible.

cc @petender @fimdim for awareness.

**Comment by petender** [comment]
Thanks @tinodo and @LuizMacedo - actually just pushed a PR which had the note in the prerequisites updated to .NET7 - but that's generic, not for our specific LabVMs

**Comment by mkennten** [comment]
This can be closed, image and instructions were updated.

**Comment by petender** [comment]
confirmed labVM (Skillable) is updated to .NET7 (and .NET8) and works fine
