### ISSUE TITLE
M09-L15-Package management with Azure Artifacts: nuget pack fails

### ISSUE THREAD

**Issue by mrstage** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#516]
### What happened?

Exercise : 01
Task: 02
Step: 16

Description of issue:
The .\nuget pack eshoponweb.shared.csproj fails as the 'pack' command has been deprecated.
Running dotnet pack eshoponweb.shared.csproj works.

Repro steps:
1. Run the following: .\nuget pack eshoponweb.shared.csproj

### Lab

Other

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
Thanks @mrstage. Finally fixing this issue, right? 😊 I'm sorry. I had other priorities to focus, and I'll try to resolve the issues faster next time. Fixed by #553.
