### ISSUE TITLE
M00-LAB02: Step Order

### ISSUE THREAD

**Issue by Skillable-Dev-Ap** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#521]
### Contact Details

Austin.priesel@skillable.com

### What should we change?

Exercise 4 Task 1 Step 4/5:

These steps are in the opposite order of how they appear in the UI.  

### Lab

Lab 02 Version controlling with Git in Azure Repos

### Relevant screenshots

None were provided during QA.

** GH pull requests is asking for repo comparisons prior to being able to submit a pull request. For simplicity purposes, will be posting Issues instead for this series/profile.

**Comment by petender** [comment]
steps validated, they are OK as described - first it asks for the name of the branch, followed by which branch head to use (main)
