### ISSUE TITLE
M03-LAB03:: Repo Policy

### ISSUE THREAD

**Issue by Skillable-Dev-Ap** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#522]
### Contact Details

Austin.priesel@skillable.com

### What should we change?

Exercise 2 Task 1 Step 18:

The student will hit an error trying to save/commit. The existing repo policies do not allow direct commits to the main branch. The policy set in the prior lab needs to be reversed.

### Lab

Lab 03 Configuring agent pools and understanding pipeline styles

### Relevant screenshots

None were provided during QA.

** GH pull requests is asking for repo comparisons prior to being able to submit a pull request. For simplicity purposes, will be posting Issues instead for this series/profile.

**Comment by petender** [comment]
fixed with PR #540

**Comment by petender** [comment]
closed after PR merge
