### ISSUE TITLE
M03-LAB03: Pipeline steps missing

### ISSUE THREAD

**Issue by Skillable-Dev-Ap** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#523]
### Contact Details

Austin.priesel@skillable.com

### What should we change?

Exercise 2 Task 1 Step 24:

There are steps missing to approve the permissions needed to run the pipeline.

### Lab

Lab 03 Configuring agent pools and understanding pipeline styles

### Relevant screenshots

None were provided during QA.

** GH pull requests is asking for repo comparisons prior to being able to submit a pull request. For simplicity purposes, will be posting Issues instead for this series/profile.

**Comment by petender** [comment]
fixed with PR #541
