### ISSUE TITLE
M03-LAB05: WebApp delayed to deploy

### ISSUE THREAD

**Issue by Skillable-Dev-Ap** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#524]
### Contact Details

Austin.priesel@skillable.com

### What should we change?

Exercise 2 task 3 step 3/4:

The Action is showing "Error: Deployment Failed, Error: Resource az400-webapp-qa doesn't exist." 

The Resource "az400-webapp-qa" app service was created in Azure but the WebApp was not deployed.

Re-running the job allows the deployment to complete. Could possibly be a time sensitive issue/awareness to have. 

### Lab

Lab 06 Deploying Docker Containers to Azure App Service web apps

### Relevant screenshots

None were provided during QA.

** GH pull requests is asking for repo comparisons prior to being able to submit a pull request. For simplicity purposes, will be posting Issues instead for this series/profile.

**Comment by petender** [comment]
This feels more like an intermediate issue, not related to the steps in the lab, but rather busy load times in Azure, maybe specific region,... tried simulating the same and worked smooth. Closing issue.
