### ISSUE TITLE
M03-LAB06: Main Branch set to deny Pushes to main and AZ container registry error

### ISSUE THREAD

**Issue by Skillable-Dev-Ap** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#525]
### Contact Details

Austin.priesel@skillable.com

### What should we change?

Exercise 2 Task 1 steps 8 & 10:

The main branch is still set to deny Pushes to main. This causes an error as written.

While in the Azure container registry the following error show while trying to view the repositories.

Status: 401. Unauthorized. 

### Lab

Lab 06 Deploying Docker Containers to Azure App Service web apps

### Relevant screenshots

None were provided during QA.

** GH pull requests is asking for repo comparisons prior to being able to submit a pull request. For simplicity purposes, will be posting Issues instead for this series/profile.

**Comment by yashints** [comment]
this has been fixed as part of other refactorings
