### ISSUE TITLE
M05-LAB10: Image unauthorized and missing step

### ISSUE THREAD

**Issue by Skillable-Dev-Ap** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#526]
### Contact Details

Austin.priesel@skillable.com

### What should we change?

Ex 1 task 1 step 7/8

7: You can not view the images in the created ACR. The following error comes up.  

"Status: 401. Unauthorized."

8:  There is a step missing, to instruct the student to toggle on the Admin user.

### Lab

Lab 10 Integrate Azure Key Vault with Azure DevOps

### Relevant screenshots

None were provided during QA.

** GH pull requests is asking for repo comparisons prior to being able to submit a pull request. For simplicity purposes, will be posting Issues instead for this series/profile.

**Comment by yashints** [comment]
This has been fixed
