### ISSUE TITLE
M09-LAB16: Cant complete using current instructions

### ISSUE THREAD

**Issue by Skillable-Dev-Ap** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#527]
### Contact Details

Austin.priesel@skillable.com

### What should we change?

Ex 2 Task 3 Steps 1-5:
- This task needs to be re-visited, the way Azure Load Testing works has changed and these steps can not be followed as written.

Ex 3 Task 5 Step 4:
- Following this step as written results in a failed pipeline. The test will not run as the config.yml file contains a duplicate key error. For "failureCriteria" 

### Lab

Lab 16 Monitoring application performance with Application Insights

### Relevant screenshots

None were provided during QA.

** GH pull requests is asking for repo comparisons prior to being able to submit a pull request. For simplicity purposes, will be posting Issues instead for this series/profile.

**Comment by petender** [comment]
fixed with PR #539

**Comment by petender** [comment]
fixed with PR #539
