### ISSUE TITLE
M03-Deploying docker containers: repository does not load 

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#531]
### What happened?

Exercise : 00
Task: 00
Step: 00

Description of issue:

For some reason learners do not get enough permission to load the images in the ACR repository. Issue is fixed giving elevated permissions such as "owner" role.

Repro steps:
1.
1.
1.

### Lab

Deploying Docker Containers to Azure App Service web apps

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
@lauraAlvEl @LuizMacedo same thing happens to "[Integrating Azure Key Vault with Azure DevOps](https://microsoftlearning.github.io/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/Instructions/Labs/AZ400_M05_L10_Integrating_Azure_Key_Vault_with_Azure_DevOps.html)"

**Comment by yashints** [comment]
@unaihuete93 I can't reproduce this, if I follow all the steps the app successfully pulls down the image. Could you give me more specifics?

**Comment by unaihuete93** [comment]
Hi Yas, when I reported it, the app was able to pull the image. But the learners could not see the images in the ACR repository from the Portal.

**Comment by yashints** [comment]
Might have been in transient issue
