### ISSUE TITLE
M09-Monitoring Application Performance with Application Insights and Azure Load Testing: Numbering and YAML broken

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#534]
### What happened?

Exercise: 01
Task: 01
Step: 12

Description of issue:
- Numbering is wrong, for Task 1 it counts to 7 and then starts again at 1. This is regarding step 12 which is currently labelled "5."
- The formatting of the yaml snippet is broken, there's some instructional text embedded in the yaml code.
- The following numbering is also broken and needs to be fixed.

### Lab

Monitoring application performance with Application Insights

### Relevant screenshots

<img width="341" alt="image" src="https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/37703728/25ffe463-d651-4c12-98fe-dc80a3f10468">

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by petender** [comment]
fixed with PR #539
