### ISSUE TITLE
M03-Configuring Agent Pools and Understanding Pipeline Styles: Instructions don't match when no pipeline has been created yet

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#535]
### What happened?

Exercise : 001
Task: 01
Step: 02

Description of issue:
The lab "Configuring Agent Pools and Understanding Pipeline Styles" is the first one in which a pipeline is created in the eShopOnWeb project if labs are done in order. Because of this, there is no "Recent" tab present but instead a central button "Create Pipeline".

We need to either add a note that in case this is the first pipeline to use a different approach or make sure that we setup a pipeline in the validation lab AND reference this in all labs. It should be possible to do the labs in any order, but especially the natural one (1-x).

### Lab

Configuring agent pools and understanding pipeline styles

### Relevant screenshots

<img width="519" alt="image" src="https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/37703728/1079c0bf-8f16-485b-9424-8a5a65cdfb24">

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by petender** [comment]
fixed with PR #538
