### ISSUE TITLE
M03-Configuring Agent Pools and Understanding Pipeline Styles: Agent Pool needs to be removed from pipeline

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#536]
### What happened?

Exercise: 03
Task: 01
Step: 04 (adding)

Description of issue:
In the lab "Configuring Agent Pools and Understanding Pipeline Styles" we import from file /.ado/eshoponweb-ci-pr.yml and label the pipeline "eShopOnWeb". In the lab we then change the file to use the created agent pool which is deleted at the end of this exercise. But the pipeline is still configured to use the pool.

Since the eshoponweb-ci-pr.yml is at least used in the following lab again, it needs to be reverted to its previous state.

Different solutions:
- working with a separate file for this pipeline (or the next)
- using a branch and revert as part of the cleanup
- manually changing the vmImage line again

### Lab

Configuring agent pools and understanding pipeline styles

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by petender** [comment]
fixed with PR #538
