### ISSUE TITLE
Sonarcloud Lab: "new code definition" moved

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#545]
### What happened?

new code definition not shown as explained in the lab
![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/64772417/5bf72cd3-4abb-4478-8bf6-cab228a0c9c8)

new way: https://docs.sonarsource.com/sonarcloud/improving/new-code-definition

### Lab

Other

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
@LuizMacedo any idea to replace this lab with CodeQL? either on GitHub or ADO

**Comment by LuizMacedo** [comment]
@unaihuete93 that's the goal! Post JTA will bring a few changes to current labs and content. I'll start working on the changes soon!

**Comment by LuizMacedo** [comment]
Closing the issue since this will be retired in our next update. Thanks.
