### ISSUE TITLE
M04-LAB07 Controlling Deployments using Classic Release Gates - problem when deploying eshoponweb new code

### ISSUE THREAD

**Issue by jajjaf** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#552]
### What happened?

Exercise 3: Configure the release pipeline
Task 1: Set Up Release Tasks
Step: Switch to the Azure portal interface, navigate to the resource group az400m04l09-RG, in the list of resources, click the DevTest web app, on the web app blade, click Browse, and verify that the web page (E-commerce website) loads successfully in a new web browser tab.

Description of issue:
the code of the e-SohopOnWeb application has been updated and when we deploy in a web app there is always the following error, does anyone have this same problem, below is a screenshot, this blocks the rest of the lab and the other labs too since it is always the same code to deploy 
thanks 
Below is a screenshot.

### Lab

Control Deployments using Release Gates

### Relevant screenshots

<img width="771" alt="error AZ-400" src="https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/70439383/4195dd93-a367-4a6c-895b-0167d16020ce">

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by jajjaf** [comment]
@LuizMacedo since the last merge, deployment is no longer done correctly in Azure webapps, this is also valid for lab 16 thanks

**Comment by LuizMacedo** [comment]
Thanks @jajjaf I'm checking it and I'll fix as soon as possible. Apparently not something with AZ-400 labs but the eShopOnWeb update.

**Comment by LuizMacedo** [comment]
Thanks @jajjaf. I'm on it and I'll fix as soon as possible.

**Comment by LuizMacedo** [comment]
It's fixed. Issue was the old bicep folder path in the .yml files from the .ado folder.

**Comment by jajjaf** [comment]
@LuizMacedo 
Thank you, even with the modified Bicep path there is an application problem, when it is pushed to a web app it still displays the same error message.
THANKS

**Comment by LuizMacedo** [comment]
Interesting. Let me reopen the issue so I can dig deeper. Thanks.

**Comment by jajjaf** [comment]
@LuizMacedo it may be a configuration problem or migration to version 8 of dotnet, and it's the same thing for a few other Labs. Thanks

**Comment by jajjaf** [comment]
@LuizMacedo @yashints Thank you for your quick interaction
I tested with the new version of the code that you recently merged,  the eshoponweb application once deployed in the web still displays the same error message the rest of the labs are blocked

**Comment by jajjaf** [comment]
@LuizMacedo yes, absolutely I redeployed with the new still the same error

<img width="774" alt="error" src="https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/70439383/7ee6e803-3b85-48e2-8515-dc46a12a876d">

**Comment by jajjaf** [comment]
@LuizMacedo @yashints  yes absolutely I redeployed with the latest version still the same error
<img width="774" alt="error" src="https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/70439383/27388f6e-7813-459e-8de0-e05fafdaacf5">

**Comment by sofiing1985** [comment]
Hello I test the lab 16 today and I can confirm that I have the same issue mentioned by @jajjaf

**Comment by LuizMacedo** [comment]
Thanks @jajjaf @sofiing1985 I'll try to check it today. The last update from @yashints should have resolved the issue. I'll check what else is missing.

**Comment by rob-foulkrod** [comment]
![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/89028299/5a22c1d4-5d88-44f0-93bc-7bc9d67698fd)

Currently, I cannot reproduce the error when I have the latest Eshop and the latest instruction set.

Make sure you are seeing Exercise 3 Task 1 Step 14 
"Open the Application and Configuration Settings pane and enter -UseOnlyInMemoryDatabase true -ASPNETCORE_ENVIRONMENT Development in the App settings box."

**Comment by LuizMacedo** [comment]
@jajjaf @sofiing1985 please, let us know if it works following @rob-foulkrod suggestion. Thanks!
