### ISSUE TITLE
M01-Agile Planning and Portfolio Management with Azure Boards: Search name for work item assignment

### ISSUE THREAD

**Issue by paul-msft** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#561]
### Contact Details

paul.ivey@microsoft.com

### What happened?

Exercise : 01
Task: 02
Step: 04

Description of issue:
The instructions say to select your user account from the drop-down list, but in a new org, you'll have to search first.

Repro steps:
1. Follow the prerequisites to create a new org etc.
1. Follow the lab steps down to Exercise 1, Task 2, Step 4
1. Make a sad face (like this 😔) because the instructions don't explain you need to click on search instead of just selecting the name from the list.

### Lab

Agile planning and portfolio management with Azure Boards

### Do you want to help us? 👏

- [x] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by rob-foulkrod** [comment]
@paul-msft Nice fix. It's a good quality of life improvement on the first lab of the course. Thanks.
