### ISSUE TITLE
M03-Implementing GitHub Actions for CI/CD

### ISSUE THREAD

**Issue by ElaMark** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#563]
### Contact Details

mark.walsh@lumifygroup.com

### What happened?

Lab: M03: Implementing GitHub Actions for CI/CD

Exercise : 01
Task: 02
Step: 06

Description of issues:

webapp.bicep attempts to create a B1 app service plan but it seems this is no longer allowed with Azure Passes (so annoying!).      Can get around it by switching to F1
     
     param sku string = 'B1' // The SKU of App Service Plan
     
This problem is not circumvented for some of my students who continue to get errors indicating there are "insufficient Cores for my subscription" even though they attempt to create the app service plan in many regions.

The problem is also in main.bicep and webapp-docker.bicep and in the instructions for the Lab: Configuring Pipelines as Code with YAML. As we find more, I'll update here

### Lab

Several labs

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by ElaMark** [comment]
The problem is also in main.bicep and webapp-docker.bicep

**Comment by massimobonanni** [comment]
It is an issue of the Azure Pass Subscriptions created this week. It is not a but related to the lab.
MS is fixing the problem.

**Comment by ElaMark** [comment]
Thanks Massimo. I figured as much although I was unsure whether the change to Azure Passes by MS was accidental or intentional. In any case I raised the issue in this repo as it will affect anybody doing the Az-400 labs
