### ISSUE TITLE
M03-Implementing GitHub Actions for CI/CD : GitHub Actions can't find the Web app that already been provisioned.

### ISSUE THREAD

**Issue by msftnutta** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#565]
### What happened?

Github actions triggered and often get the error as shown the screen shot.

App Service Plan, App Services, all correct but it failed at this pointed too often before succeeding it.

### Lab

Other

### Relevant screenshots

![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/98095529/e82624b2-b8c1-4707-967d-c2919ead59dc)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by mrstage** [comment]
Had the same thing this week. 10 - 15 minutes was the wait time before it appeared.

**Comment by maartenvandiemen** [comment]
Looks like the same issue that affects the Azure Pipeline task: https://github.com/microsoft/azure-pipelines-tasks/issues/15532. Solution for me was to use the command-line, which isn't affected by this issue. https://github.com/maartenvandiemen/TodoItems/blob/main/.github/workflows/main.nodocker.yml (line 86, 87).

If people agree I can make a PR to use the command-line instead of the out-of-the-box tasks.

**Comment by yashints** [comment]
@maartenvandiemen go for it

**Comment by maartenvandiemen** [comment]
@yashints to start with I created PR: https://github.com/MicrosoftLearning/eShopOnWeb/pull/140. In webapps-deploy@v3 the upgrade mechanism is changed, so maybe this will fix the issue already. If not please give feedback and I will do the change as suggested above.

**Comment by yashints** [comment]
thanks, I will need to test these first

**Comment by rob-foulkrod** [comment]
> ... to start with I created PR: [MicrosoftLearning/eShopOnWeb#140](https://github.com/MicrosoftLearning/eShopOnWeb/pull/140). In webapps-deploy@v3 the upgrade mechanism is changed, so maybe this will fix the issue already. If not please give feedback and I will do the change as suggested above.

@maartenvandiemen,  I think the upgrade is helpful, however, I have my doubts that this will have any impact of the issue at hand. Azure/webapps-deploy@v3 was released in October of last year, and issues are still being raised as of February of the current year. In addition, nothing in the list of difference between v2 and v3 mention dealing with the caching issue of the API call. If you have the I think we would love to take a look at a CLI based deploy.

**Comment by maartenvandiemen** [comment]
@rob-foulkrod thanks for the feedback. I will do the change next week and update the PR. For the other tasks I think it's good to keep them on the maximum major version.

**Comment by LuizMacedo** [comment]
PR approved. Closing the issue for now, let me know if you still see it.

**Comment by maartenvandiemen** [comment]
@LuizMacedo @rob-foulkrod @yashints I didn't have time to update PR: https://github.com/MicrosoftLearning/eShopOnWeb/pull/140 with the CLI approach. But it's stil on my list. (In my opinion it's better to have it in separate PR's). I will leave it up to you to reopen this issue or not.

**Comment by LuizMacedo** [comment]
Thanks, @maartenvandiemen! I agree, a separate PR is good.

**Comment by maartenvandiemen** [comment]
@LuizMacedo @rob-foulkrod @yashints created CLI based deployment in above PR. I haven't heard anyone who experienced this issue after the upgrade of Github tasks.

**Comment by rob-foulkrod** [comment]
Thanks for the contribution @maartenvandiemen. I will take a look at it this weekend. And I agree, I have never had a problem pushing a site with the CLI tooling.
