### ISSUE TITLE
M08_L14_Monitor_Application_Performance_with_Azure_Load_Testing ("WorkloadIdentityFederation" is not supported") issue

### ISSUE THREAD

**Issue by ahsan296** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#571]
### What happened?

Exercise : 02
Task: 04
Step:15

Description of issue:
UnhandledPromiseRejectionWarning: Auth Scheme "WorkloadIdentityFederation" is not supported.

**The same issues is already reported at this Microsoft below link:** 
https://developercommunity.visualstudio.com/t/AzureLoadTest1---UnhandledPromiseReject/10494725?pageSize=15&sort=active

What's the update about it?

**The Screenshot have attached below:**
![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/142339674/464e7d59-2663-4517-98e9-34c4589ac0b1)

### Lab

Other

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by rob-foulkrod** [comment]
As stated in your referenced link, WWorkloadIdentityFederation Service Connections are not yet supported. The current lab instructions have you Create an automatic Service Principal from the 'Authorize' option. If your previously created Service principal is of the WIF verity you may get this message. 

Until WorkloadIdentityFederation service connection are supported, use the inline Authorize option.

Instruction could be more clear about strongly suggesting a service connection created inline or a manual Service Connection.
