### ISSUE TITLE
M02-Configure agent pools and understanding pipeline styles

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#575]
### Contact Details

steve@wigf1.net

### What happened?

Exercise : 02
Task: 01
Step: 21

Description of issue:

The lab says to replace line 13 which says vmImage: windows-latest

However, line 13 actually contains vmImage: ubuntu-latest

This confuses students because at first glance they think they need to change the line from ubuntu to windows.

It should read

On the eShopOnWeb edit pane, in the existing YAML-based pipeline, replace line 13 which says vmImage: ubuntu-latest designating the target agent pool the following content, designating the newly created self-hosted agent pool:

### What happened?

Exercise : 02
Task: 01
Step: 22

Description of issue:

After changing the YAML, there is no 'Save and Run' in the UI. student should be directed to click 'Validate and save'

![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/12164329/4ee2c4c6-4d99-4141-93b2-d38faf853b31)

They will also then need to click Run twice.

### What happened?

Exercise : 03
Step: 04

Description of issue:

Students are directed to return the YAML to its original state, however, that would require entering ubuntu-latest on line 13, not windows-latest as instructed.

![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/12164329/0ddf0460-6071-47ed-b41c-86fe556982c2)

### Lab

Configuring agent pools and understanding pipeline styles

### Relevant screenshots

![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/12164329/64d8df2e-e95f-4100-8ede-7fe436a70b1f)

![image](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/12164329/2a45d4a0-2f9c-4de5-b3b9-14979007f538)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by ahsan296** [comment]
Recently I made this lab accordingly now its workable fine.

**Comment by LuizMacedo** [comment]
@WigF1 it is fixed. Please, next time create separate issues for tracking purposes. Thanks.
