### ISSUE TITLE
M02_L05-Implement Github Actions: update deprecated login procedure

### ISSUE THREAD

**Issue by fernandoroa** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#577]
### Contact Details

froao@unal.edu.co

### What happened?

After using:

```
az ad sp create-for-rbac --name NAME --role contributor \
 --scopes /subscriptions/SUBSCRIPTION --sdk-auth
 ```

Description of issue:

A "warning" appears:
'Option '--sdk-auth' has been deprecated and will be removed in a future release.'

Follow:
https://microsoftlearning.github.io/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/Instructions/Labs/AZ400_M02_L05_Implement_GitHub_Actions_for_CI_CD.html

Until the command above

### Lab

Implementing GitHub Actions by using DevOps Starter

### Relevant screenshots

Relevant md:  
```
Instructions/Labs/AZ400_M02_L05_Implement_GitHub_Actions_for_CI_CD.md
```
 

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by yashints** [comment]
This is not a bug related to the lab, please follow this thread for more information:

https://github.com/Azure/azure-cli/issues/20743
