### ISSUE TITLE
M03-LABNAME: Configure Pipelines as Code with YAML

### ISSUE THREAD

**Issue by DanePillay-nel** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#579]
### Contact Details

dane@live.co.za

### What happened?

Exercise : 0
Task: 02 Task 2: Create Azure resources
Step: 05

Description of issue: Seems like Azure pass is not being allowed to create Azure app service plan.
Error message: The subscription '99f4fa0d-e0cb-461d-a88e-8aacc8af9f49' is not allowed to create or update the serverfarm.

Repro steps:
1.Followed steps in lab plus tried and tested using an msdn account.
2.I am able to create in msdn just not azure pass.

### Lab

Configuring pipelines as code with YAML

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by yashints** [comment]
We're working on a fix and will update soon, please be patient

**Comment by LuizMacedo** [comment]
We are still working to find the best way to resolve this issue.

**Comment by LuizMacedo** [comment]
As I mention in #5764, I'm still working to make our labs work in Cloud Slice so hopefully really soon we won't need Azure Passes and this issue shouldn't happen again.

**Comment by LuizMacedo** [comment]
@DanePillay-nel did you see the issue happening again recently? Thanks.

**Comment by prabhjotsinghbakshi** [comment]
This lab is working fine for me. With CloudSlice ( LOD) - dated 23rd July 24

**Comment by LuizMacedo** [comment]
Awesome, thanks @prabhjotsinghbakshi. I'll be closing the issue for now. Let me know if you see anything happening and I'll be happy to help. Thanks!
