### ISSUE TITLE
M07-Package Management with Azure Artifacts

### ISSUE THREAD

**Issue by magicsst** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#580]
### Contact Details

sakis@siklarlis.gr

### What happened?

Exercise 1: Working with Azure Artifacts
Task 2: Creating and publishing an in-house developed NuGet package
Step: 15

The eShopOnWebShared feed does not include the published nuget package

### Lab

Other

### Relevant screenshots

![εικόνα](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/assets/46692568/a0f78e1c-400e-4ad3-8831-d3cb9bdb5ce4)

### Do you want to help us? 👏

- [X] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by yashints** [comment]
@magicsst thanks for raining this, would you happen to have the pipeline and logs from your lab? We can't figure out what has been the issue unless we have more information from your lab environment. If you have the full pipeline or any logs that would help a lot

**Comment by LuizMacedo** [comment]
@magicsst please, let us know if you can reproduce the issue and send us the log. Thanks.

**Comment by LuizMacedo** [comment]
We were unable to reproduce the issue and we don't have enough data to troubleshoot. Please let me know if this happens again. Thanks.
