### ISSUE TITLE
M06-L12-EX01-TASK02-STEP04: Repo folder change (bicep --> infra) not updated with image

### ISSUE THREAD

**Issue by christiannagel** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#591]
### Contact Details

christian@christiannagel.com

### What happened?

Exercise : 01
Task: 02
Step: 04

Description of issue:

Pull request #564 updated a folder name (bicep --> infra) and updated 1 image but missed another image. The image with step 4 needs an update as well.

This image *Instructions/Labs/images/m06/newfile.png* still shows the 'bicep` folder:

### Lab

Deployments using Azure Bicep templates

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
Fixed. Thanks!
