### ISSUE TITLE
M01_L01_Agile_Plan_and_Portfolio_Management_with_Azure_Boards: Wrong colored card

### ISSUE THREAD

**Issue by Neophear** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#593]
### Contact Details

stiiggade@gmail.com

### What happened?

Exercise : 01
Task: 03
Step: 15

Description of issue:
Image shows two green cards, but one of them is a Design-activity, and only Development-activities should be green, which confuses the reader.

Repro steps:
N/A

### Lab

Agile planning and portfolio management with Azure Boards

### Relevant screenshots

![image](https://github.com/user-attachments/assets/89ac6bbf-9c80-4857-948a-b9758e1d1644)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
Lab updated today. Closing the issue. Thanks!
