### ISSUE TITLE
Lab Package Management with Azure Artifacts

### ISSUE THREAD

**Issue by azurearchitect786** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#597]
### What happened?

The package dotnet pack command is not working We get error

![image](https://github.com/user-attachments/assets/2ab24025-c169-4187-9a90-e6a821b93f0b)

### Lab

Package management with Azure Artifacts

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by yashints** [comment]
@LuizMacedo  @rob-foulkrod this is due to not having the credential manager installed, which is a little bit confusing, since we asked them to use Visual Studio to add the feed but then revert back to terminal for packing, if they pack using VS it would be OK. Thoughts?

**Comment by dave-007** [comment]
Hi,
So if Task 2 step 8 guides the student to run the commands from the Visual Studio Developer Command Prompt instead of PowerShell prompt, will it work?

**Comment by rob-foulkrod** [comment]
Recreating the lab with the credential provider installed and it looks as if building in Visual Studio did not authenticate against the feed. So options are to pack with Visual Studio as @yashints mentioned, or to 
`dotnet pack .\eshoponWeb.Shared.csproj --interactive`
then follow the instructions and authenticate with the devicecode.

Either way, looks like we will need to tweak the instructions.

**Comment by LuizMacedo** [comment]
Lab updated today. Closing the issue. Thanks!
