### ISSUE TITLE
Lab 10: Controlling deployments using release gates   -- Wrong instructions

### ISSUE THREAD

**Issue by AndrewConniff** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#60]
# Module: 10
#### Step: 01

Description of issue
The instructions are not clear- all pipelines is the page but not helpful when not on the page. Additionally, the instructions say to go to the left oval for post deployment settings, and post deployment settings are on the right hand side of the rectangle.

Recommend explicit path to the pipeline and correct instructions on getting to the gate....

Repro steps:

1.
1.
1.

**Comment by krasmuss** [comment]
Updated Exercise 2, Task 2, Step 1 to indicate that the Post-deployment conditions is on the right edge of the rectangle.

We have engaged with lab testers to ensure that the remaining steps are correct.
