### ISSUE TITLE
M03_L08_Control_Deployments_using_Release_Gates Move to YAML release

### ISSUE THREAD

**Issue by maartenvandiemen** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#602]
### Contact Details

maarten.vandiemen@infosupport.com

### What should we change?

M03_L08 is currently focused on the old release pipeline, which isn't enabled by default in new Azure Devops organizations. With the current feature set in Azure Devops I think we can migrate this lab fully to YAML.

I'm willing to make the changes suggested above. But only if there're no plans to remove this lab in the near future. If I have confirmation a PR can be expected soon.

### Lab

Lab 07 Control Deployments using Release Gates

### Relevant screenshots

paste here 😉

**Comment by LuizMacedo** [comment]
Thanks @maartenvandiemen. I updated all labs today and we will have more changes soon, including in this lab. Closing the issue/feedback for now.
