### ISSUE TITLE
M02-LABNAME: Configure agent pools and understanding pipeline styles

### ISSUE THREAD

**Issue by tiagocostapt** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#603]
### What happened?

Last screenshot needs to be replaced as it show a windows-latest agent and according to the instructions it should be ubuntu-latest.

### Lab

Configuring agent pools and understanding pipeline styles

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
Thanks @tiagocostapt!
