### ISSUE TITLE
ADO dashboard defaults to GitHub and instructions don't address this

### ISSUE THREAD

**Issue by AndrewConniff** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#61]
# Module: 10
#### Step: 01

Description of issue
The portal defaults to authorizing with git hub and the instructions do not say to switch it to DevOps (there is a link in the UI) 
This causes much confusion and time to figure it out.

Repro steps:

1. start the lab
1. follow instructions
1. notice the github auth

**Comment by mkennten** [comment]
This has been fixed in PR #69
