### ISSUE TITLE
M03-L08: Release pipelines

### ISSUE THREAD

**Issue by LewisGoDeploy** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#616]
### What happened?

Exercise 2, Task 1: Set Up Release Tasks

"From the eShopOnWeb project in the Azure DevOps portal, in the vertical navigational pane, select Pipelines and then, within the Pipelines section, click Releases."

I believe release pipelines have been depreciated, can you confirm what the new steps in this guide will be?

### Lab

Other

### Relevant screenshots

![image](https://github.com/user-attachments/assets/afcfc935-cab2-4dad-8461-3ba1d86c84aa)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment]
you can reenable at **Organization settings > Pipelines > Settings > (OFF) Disable the creation of classic x pipelines**

**Comment by LewisGoDeploy** [comment]
Thank you, had a feeling there was an option somewhere!

**Comment by LuizMacedo** [comment]
@LewisGoDeploy, @unaihuete93 is correct. Make sure you follow the [AZ400_M00_Validate_lab_environment](https://microsoftlearning.github.io/[AZ400-DesigningandImplementingMicrosoftDevOpsSolutions](https://microsoftlearning.github.io/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/Instructions/Labs/AZ400_M00_Validate_lab_environment.html)/Instructions/Labs/AZ400_M00_Validate_lab_environment.html) and "Toggle the switch to Off for Disable creation of classic build pipelines and Disable creation of classic release pipelines".

**Comment by LewisGoDeploy** [comment]
Thank you, please note though that your hyperlink is no longer available @LuizMacedo

**Comment by LuizMacedo** [comment]
@LewisGoDeploy here https://microsoftlearning.github.io/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/Instructions/Labs/AZ400_M00_Validate_lab_environment.html.
