### ISSUE TITLE
create Azure project wiki

### ISSUE THREAD

**Issue by DrIffathsultana** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#62]
# Module: 02
#### Step: 7

Description of issue
I am not able to see Create project button after step 6

![Screen Shot 2021-03-29 at 3 35 49 PM](https://user-images.githubusercontent.com/75779290/112908488-752f4300-90a4-11eb-9ff5-dbb23a7d2ce5.png)

Repro steps:
1.
1.
1.

**Comment by mkennten** [comment]
You don't have the button yet, because there's no organization selected.
