### ISSUE TITLE
M08-LAB14: Load Testing instant cost should be mentioned prominently

### ISSUE THREAD

**Issue by sbonds** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#620]
### Contact Details

sbonds@gmail.com

### What should we change?

PROPOSAL

The lab instructions for M08 L14 Monitor application performance with Azure Load Testing should mention that there will be a significant, non-pro-rated cost when the Load Test resource is created. (Currently $10.) It's unusual for labs to use resources that are instant cost, and this could come as a shock to others like it did for me.

### Lab

Lab 16 Monitoring application performance with Application Insights

### Relevant screenshots

![2024-11-23 23_23_35-Steve Bonds - Microsoft Azure](https://github.com/user-attachments/assets/5787ec3d-c710-4df5-a3ea-c8d58658730e)

**Comment by LuizMacedo** [comment]
@sbonds thank you so much! I agree, and I’m adding an **"> Important"** note before creating the resource to prevent any billing surprises.

**Comment by LuizMacedo** [comment]
Note added #629. Thanks for the feedback!
