### ISSUE TITLE
Lab 13 (https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/Instructions/Labs/AZ400_M07_L13_Package_Management_with_Azure_Artifacts.md)

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#621]
### What happened?

I'm trying to understand the flow of the Instructions for this lab.  I am unable to get a test instance to flow past Exercise 1/Task 4/Step 9, as it fails with errors.  

In Task 3/Step 1, we add package for Newtonsoft.json within our Visual Studio 2022 instance.  Because previous instructions have us logged in and connected to the DevOps Org/Project we are working in, this appears to have the effect of updating our https://dev.azure.com(org)/(project) artifacts with the new package automatically, alongside the earlier eShopOnWeb.Shared package. 

In Task 4/Step 3, it fails, but it does not appear to be failing for the same reason the Instructions state - instead of the expected 409 *'Conflict - 'Newtonsoft.Json 1.3.0.17' cannot be published to the feed because it exists in at least one of the feed's upstream sources.'*, I instead get error *'(Conflict - The feed already contains 'Newtonsoft.Json 13.0.3'* which seems to make sense as this is exactly what we have done by-design in the previous Instructions, no?

The subsequent steps succeed, in that I can search for Newtonsoft.json and find it in my upstream sources, I can delete it and save successfully, but in Task 4/Step 9 it still errors for the same reason - package already present. 

If I attempt to 'creatively' workaround this by trying to unlist/delete the Newtonsoft.json from the Artifacts page, this also does not help as now I get error *'(Conflict - The version 13.0.3 of Newtonsoft.Json has been deleted. It cannot be restored or pushed.'* 

Am I completely misunderstanding how this lab is intended to work?  Cant seem to get by the issue no matter what I've tried....

### Lab

Package management with Azure Artifacts

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by LuizMacedo** [comment]
I’ll provide more details by email. For anyone encountering this issue, I’ll be removing Task 4 to reduce lab timing and improve the experience, as it is largely redundant with the previous tasks.
