### ISSUE TITLE
Change in Azure Pipelines Grant for Private Projects

### ISSUE THREAD

**Issue by AndrewTier1Point5** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#63]
# Module: 06
##### Step: 16

Description of issue:
A recent Microsoft blog post has brought up a concern that might effect some AZ-400 participants, https://devblogs.microsoft.com/devops/change-in-azure-pipelines-grant-for-private-projects/

There is now a chance for some participants to not be granted the free tier of 1800 minutes in private projects which has caused issues when attempting portions of the course (Module 6 is one example). The error that occurs when this section is attempted without the free tier was  `"the agent request is not running because you have reached the maximum number of requests that can run for parallelism type 'Microsoft-Hosted-Private'. Current position in queue: 1"` which can make troubleshooting difficult without being aware of the recent change.

The blog post proceeds to tell users to reach out to "azpipelines-freetier@microsoft.com" with the users name and the name of the DevOps organization to have the free tier applied to your organization.

**Comment by krasmuss** [comment]
This was addressed in the March 26 release of the course. Additions were made to the change log and the Trainer Prep Guide to clarify the steps necessary to ensure that all students are granted the free tier of 1800 minutes in private projects.

**Comment by Usamawahabkhan** [comment]
still have this error

**Comment by unaihuete93** [comment]
Send an email as shown in the article blog (or link an azure subscription + pay for a private pipeline while waiting for a response): https://devblogs.microsoft.com/devops/change-in-azure-pipelines-grant-for-private-projects/
