### ISSUE TITLE
Lab05 not possible to run on 

### ISSUE THREAD

**Issue by tiagocostapt** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#67]
# Module: 05

Can't do the Microsoft-hosted agents related taks has Microsoft changed the policy on new free acccounts.
Can you do some edits on the steps 

Information: https://devblogs.microsoft.com/devops/change-in-azure-pipelines-grant-for-private-projects/

**Comment by unaihuete93** [comment]
Send an email as shown in the article blog (or link an azure subscription + pay for a private pipeline while waiting for a response): https://devblogs.microsoft.com/devops/change-in-azure-pipelines-grant-for-private-projects/

**Comment by krasmuss** [comment]
This has been resolved.
