### ISSUE TITLE
Agent parallelism issues on Lab - Module 6

### ISSUE THREAD

**Issue by cdanvergara** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#68]
# Module: 06
#### Step: 7 On the Summary tab of the build job’s pane, verify that the build completed successfully.

Description of issue: 

The task doesn't complete successfully, instead students get the following error message:
![image](https://user-images.githubusercontent.com/6410720/116312306-44612d00-a77a-11eb-934f-2a5b10e90ac6.png)

Repro steps:

We completed the required Lab preparation and the billing is setup as follows:
![image](https://user-images.githubusercontent.com/6410720/116312738-d9642600-a77a-11eb-914b-afafbd9af972.png)

However, students are still experiencing the issue. For the other labs while using Azure repos, pipelines can run without issues. The problem is just with GitHub, maybe change the project to Public to leverage the free tier?

**Comment by JuanQuijano** [comment]
The solution is simple. When we make the project, the wizard dont configure the project like private project finally. We need to go to Project settings and change the visibility from public to private.
AzureDevops dont assign paralles agents to publica visibility projects.

**Comment by cdanvergara** [comment]
Thanks for the follow-up, actually based on the instructions the project is created as Private and that's when were experiencing the problem from the screenshot.
As a workaround I switched the project to Public and then back to Private, that worked.
During the last two weeks I have not experienced this issue again, so I'll proceed and close this issue.
