### ISSUE TITLE
Typo in lab instructions

### ISSUE THREAD

**Issue by smartdevskill** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#79]
# Module: 00
## Lab/Demo: Implementing GitHub Actions by using DevOps Starter
Student lab manual
#### Step: 14

Description of issue
Step 14 says:  Change the line 20 to <div class="description line-1"> GitHub Workflow has been successfully updated</div>.
It should be line 19 makes better sense.

Repro steps:

1.
1.
1.

**Comment by krasmuss** [comment]
Fixed.
