### ISSUE TITLE
Module 10, Lab 2 - Instruction missing to change DevOps Starter setting from GitHub to Azure DevOps

### ISSUE THREAD

**Issue by jbburgess** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#80]
# Module: 10
#### Step: 03

Description of issue

This lab requires that the DevOps Starter be created using Azure DevOps rather than GitHub. GitHub is the default option that's selected, so there needs to be steps added in Task 1, between Steps 2 and 3, to open the **DevOps starter settings** blade and change it to Azure DevOps, similar to in Module 08 Lab 01, Implementing GitHub Actions by using DevOps Starter, which has the following instructions in Task 1 to confirm that GitHub is selected (though in this case, we need to actually change it):

> 3. On the **Start fresh with a new application** page of the **DevOps Starter** blade, click the **here** link in the **Setting up DevOps starter with GitHub, click here** text.
> 
> **Note:** This will display the **DevOps starter settings** blade.
> 
> 4. On the **DevOps starter settings blade**, ensure that the **GitHub** tile is selected and click **Done**.

If the instructions are followed as written, users will hit their first roadblock in Task 1, Step 4 when they are told to flip the **Add a database** slider to On, as that slider is not present on a GitHub starter. All the remaining instructions assume the starter was created in Azure DevOps.

Repro steps:

1. Follow the instructions as written up through Step 4.

**Comment by mkennten** [comment]
The instructions were fixed with PR #69. Closing this.
