### ISSUE TITLE
Lab 11b Module 11 IIS install failed due to earlier script, so Selenium won't run

### ISSUE THREAD

**Issue by smartdevskill** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#82]
# Module: 11
#### Step: 06

Description of issue:
"Once the Selenium test execution phase starts, monitor the web browser tests.",  However user will likely to see this error
"[error]Cannot find appcmd.exe location. Verify IIS is configured on az40011bvm and try operation again."

Due to few issues with the Powershell script that sets up the VM.
https://raw.githubusercontent.com/microsoft/azuredevopslabs/master/labs/vstsextend/selenium/armtemplate/chrome_firefox_VSTSagent_IIS.ps1

#copy geckodriver
Invoke-WebRequest https://github.com/Microsoft/almvm/blob/master/labs/vstsextend/selenium/armtemplate/geckodriver.exe?raw=true -OutFile "C:\Program Files\Mozilla Firefox\geckodriver.exe"

This line could fail due to TLS certificate with Invoke-WebRequest command.   Then the last line to install IIS will not run.  User will see "[error]Cannot find appcmd.exe location. Verify IIS is configured on az40011bvm and try operation again." and can't see the Selenium test run in browsers.

Also the next section installs the local agent, the exe version is out of date and not needed, because we installed the agent earlier in Task 1, Configure a self-hosted Azure DevOps agent

Fix:
1. Fixed the potential TLS issue with the Invoke-WebRequest command or move the IIS install line to earlier location in the script.
2. Remove the section to install the outdated Agent exe.

Repro steps:

1.
1.
1.

**Comment by krasmuss** [comment]
under review

**Comment by kobi86** [comment]
Any update on this issue?

**Comment by kobi86** [comment]
Hey @krasmuss, any update on this issue?

**Comment by unaihuete93** [comment]
this lab will be most probably retired, it has not been updated since moved from https://azuredevopslabs.com//labs/vstsextend/selenium/. I more updated version can be found on https://docs.microsoft.com/en-us/learn/modules/run-functional-tests-azure-pipelines/

**Comment by kobi86** [comment]
OK, so if this is the case we can close this issue :)

**Comment by unaihuete93** [comment]
Lets close it for now, there is going to be some restructuring during Jan-Feb. If we keep it, it will be renewed ;)
