### ISSUE TITLE
Please, please, please, please add screenshots to all lab instructions. Thanks.

### ISSUE THREAD

**Issue by gitet** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#91]
Screenshots will make it easier to navigate in the portal 
(and also makes it easier to navigate the lab - screenshots are strong visual cues when going back and forth between lab guide and Azure Portal / ADO Portal)

**Comment by krasmuss** [comment]
Hello, @gitet. 

Thanks for your suggestion. Screenshots have been added to the lab for module 1. We are hesitant to add screen shots because of the difficulty in keeping those screenshots up to date. We are testing this on a few modules, though. I appreciate your suggestion.
