### ISSUE TITLE
Lab 4 Module 4: Instructions should clarify what (not) to do when Lab 2 was completed already

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#93]
# Module: 04
### Task: 01

Description of issue
It should be made clear that if one followed the flow and already did complete the lab for Module 2 that the steps up to Exercise 2 are not required anymore (creating a project, cloning the repo).

**Comment by krasmuss** [comment]
This has been added to Lab 04.
