### ISSUE TITLE
Module 2 and Module 4 are identical

### ISSUE THREAD

**Issue by behymerd** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#97]
Hi, 

Are Modules 02 and 04 supposed to be duplicates of one another?

**Comment by mkennten** [comment]
These are not duplicated - the first half (Ex 0 - 1) is the same but then Mod 4 as different exercises/tasks than Mod 2:

Mod 2:
![image](https://user-images.githubusercontent.com/37703728/123046699-b5306880-d3fc-11eb-993e-503916a94e13.png)

Mod 4:
![image](https://user-images.githubusercontent.com/37703728/123046736-bfeafd80-d3fc-11eb-88bd-f5ecf3245a84.png)

**Comment by krasmuss** [comment]
This was resolved by LODS.
